openapi: 3.0.3
info:
  title: DotAAS Part 2 | HTTP/REST | Submodel Repository Service Specification - Basic Profile
  description: The basic profile of the Submodel Repository Service Specification as part of Details of the Asset Administration Shell Part 2
  contact:
    name: Constantin Ziesche, Andreas Orzelski, Florian Krebs, Bastian Rössl, Manuel Sauer, Jens Vialkowitsch, Michael Hoffmeister, Torben Miny, Sebastian Bader, Marko Ristin, Nico Braunisch
  version: V3.0-BasicProfile
  termsOfService: https://github.com/admin-shell-io/aas-specs
servers:
- url: '{protocol}://{host_name}:{port}/api/{version_prefix}'
  variables:
    protocol:
      description: 'Allows access through http and https (recommended)'
      enum:
        - 'http'
        - 'https'
      default: 'https'
    host_name:
      default: admin-shell.io
      description: 'Hostname of server hosting the api'
    port:
      enum:
        - '80'
        - '443'
      default: '443'
      description: '80 is default for http, 443 for https'
    version_prefix:
      enum:
        - 'v3'
      default: v3
paths:
  /submodels:
    get:
      tags:
        - Submodel Repository API
      summary: Returns all Submodels
      operationId: GetAllSubmodels
      x-semanticIds:
        - https://admin-shell.io/aas/API/GetAllSubmodels/3/0
        - https://admin-shell.io/aas/API/GetAllSubmodelsBySemanticId/3/0
        - https://admin-shell.io/aas/API/GetAllSubmodelsByIdShort/3/0
      parameters:
        - $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/parameters/SemanticId'
        - name: idShort
          in: query
          description: The Submodel’s idShort
          required: false
          style: form
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: Requested Submodels
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0#/components/schemas/Submodel'
        '400':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/bad-request'
        '403':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/forbidden'
        '500':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/internal-server-error'
        default:
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/default'
    post:
      tags:
        - Submodel Repository API
      summary: Creates a new Submodel
      operationId: PostSubmodel
      x-semanticIds:
        - https://admin-shell.io/aas/API/PostSubmodel/3/0
      requestBody:
        description: Submodel object
        content:
          application/json:
            schema:
              $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0#/components/schemas/Submodel'
        required: true
      responses:
        '201':
          description: Submodel created successfully
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0#/components/schemas/Submodel'
        '400':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/bad-request'
        '403':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/forbidden'
        '500':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/internal-server-error'
        default:
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/default'
  /submodels/{submodelIdentifier}:
    get:
      tags:
        - Submodel Repository API
      summary: Returns a specific Submodel
      operationId: GetSubmodelById
      x-semanticIds:
        - https://admin-shell.io/aas/API/GetSubmodelById/3/0
      parameters:
        - name: submodelIdentifier
          in: path
          description: The Submodel’s unique id (UTF8-BASE64-URL-encoded)
          required: true
          style: simple
          explode: false
          schema:
            type: string
            format: byte
      responses:
        '200':
          description: Requested Submodel
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0#/components/schemas/Submodel'
        '400':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/bad-request'
        '403':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/forbidden'
        '404':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/not-found'
        '500':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/internal-server-error'
        default:
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/default'
    put:
      tags:
        - Submodel Repository API
      summary: Updates an existing Submodel
      operationId: PutSubmodelById
      x-semanticIds:
        - https://admin-shell.io/aas/API/PutSubmodelById/3/0
      parameters:
        - name: submodelIdentifier
          in: path
          description: The Submodel’s unique id (UTF8-BASE64-URL-encoded)
          required: true
          style: simple
          explode: false
          schema:
            type: string
            format: byte
        #- $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/parameters/Level'
        - name: level
          in: query
          description: Determines the structural depth of the respective resource content
          required: false
          schema:
            type: string
            default: deep
            enum:
              - deep # only 'deep' is allowed for PUT
              #- core 
      requestBody:
        description: Submodel object
        content:
          application/json:
            schema:
              $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0#/components/schemas/Submodel'
        required: true
      responses:
        '204':
          description: Submodel updated successfully
        '400':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/bad-request'
        '403':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/forbidden'
        '404':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/not-found'
        '500':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/internal-server-error'
        default:
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/default'
    patch:
      tags:
        - Submodel Repository API
      summary: Updates an existing Submodel
      operationId: PatchSubmodelById
      x-semanticIds:
        - https://admin-shell.io/aas/API/PatchSubmodelById/3/0
      parameters:
        - name: submodelIdentifier
          in: path
          description: The Submodel’s unique id (UTF8-BASE64-URL-encoded)
          required: true
          style: simple
          explode: false
          schema:
            type: string
            format: byte
        #- $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/parameters/Level'
        - name: level
          in: query
          description: Determines the structural depth of the respective resource content
          required: false
          schema:
            type: string
            default: core
            enum:
              #- deep 
              - core # only 'core' is allowed for PATCH
      requestBody:
        description: Submodel object
        content:
          application/json:
            schema:
              $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0#/components/schemas/Submodel'
        required: true
      responses:
        '204':
          description: Submodel updated successfully
        '400':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/bad-request'
        '403':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/forbidden'
        '404':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/not-found'
        '500':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/internal-server-error'
        default:
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/default'
    delete:
      tags:
        - Submodel Repository API
      summary: Deletes a Submodel
      operationId: DeleteSubmodelById
      x-semanticIds:
        - https://admin-shell.io/aas/API/DeleteSubmodelById/3/0
      parameters:
        - name: submodelIdentifier
          in: path
          description: The Submodel’s unique id (UTF8-BASE64-URL-encoded)
          required: true
          style: simple
          explode: false
          schema:
            type: string
            format: byte
      responses:
        '204':
          description: Submodel deleted successfully
        '400':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/bad-request'
        '403':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/forbidden'
        '404':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/not-found'
        '500':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/internal-server-error'
        default:
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/default'
  /description:
    get:
      tags:
        - Description API
      summary: Returns the self-describing information of a network resource (Description)
      operationId: GetDescription
      x-semanticIds:
        - https://admin-shell.io/aas/API/Descriptor/GetDescription/3/0
      responses:
        '200':
          description: Requested Description
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/schemas/Description'
        '403':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/forbidden'