# OpenAPI version identifier - required for OpenAPI 3.0 domains
openapi: 3.0.3
info:
  title: DotAAS Part 2 | DIN SPEC 16593 | Schemas
  description: The schemas implementing DIN SPEC 16593
  contact:
    name: Michael Hoffmeister, Torben Miny, Andreas Orzelski, Manuel Sauer, Constantin Ziesche, Sebastian Bader, Marko Ristin, Nico Braunisch
  version: V1.0RC03
  termsOfService: https://github.com/admin-shell-io/aas-specs
components: 
  schemas: 
    Endpoint: 
      properties: 
        interface: 
          type: string
        protocolInformation: 
          $ref: "#/components/schemas/ProtocolInformation"
      required: 
        - protocolInformation
        - interface
      type: object
    ProtocolInformation: 
      properties: 
        endpointAddress: 
          type: string
        endpointProtocol: 
          type: string
        endpointProtocolVersion: 
          type: string
        subprotocol: 
          type: string
        subprotocolBody: 
          type: string
        subprotocolBodyEncoding: 
          type: string
        securityAttributes:
          type: array
          items:
            $ref: "#/components/schemas/SecurityAttribute"
      required: 
        - endpointAddress
      type: object
    SecurityAttribute:
      type: object
      properties: 
        type: 
          type: string
        key: 
          type: string
        value: 
          type: string
