@startuml
!pragma useIntermediatePackages false
skinparam classAttributeIconSize 0

hide methods 

class Query {
    +select: SelectField[0..1]
    +condition: Condition[1]
}
 
Query ..> SelectField
Query ..> Condition

' to better arrange the SelectField
SelectField -r[hidden]- Placeholder1
Placeholder1 -r[hidden]- Condition
hide Placeholder1

' to better arrange the elements
Placeholder2 -l[hidden]- Condition
hide Placeholder2
 
enum SelectField {
     id
}


  class Condition {
  }

  enum logicalOperation <<enumeration>> {
    $and
    $or
    $not
    nested
  }

  class logicalExpression {
    +operation: logicalOperation[1]
    +operands: Condition[1..*]
  }

  class match {
    +operands: Condition[1..*]
  }

  enum comparisonOperation <<enumeration>> {
    $eq
    $ne
    $gt
    $ge
    $lt
    $le
  }
  enum dataType <<enumeration>> {
    String
    Numerical
    DateTime
    Time
  }
  class comparison {
    +type: dataType[1]
    +operation: comparisonOperation[1]
    +operands: comparisonOperand[2]
  }

  enum stringOperation <<enumeration>> {
    $contains
    $starts-with
    $ends-with
    $regex
  }
  class stringExpression {
    +operation: stringOperation[1]
    +operands: stringOperand[2]
  }

  enum BoolLiteral <<enumeration>> {
    true
    false
  }
  class castToBool {}

  Condition <.d.> logicalExpression
  logicalExpression ..> logicalOperation
  stringExpression ..> stringOperation
  Condition ..> comparison
  Condition <..> match
  comparison ..> dataType
  comparison ..> comparisonOperation
  Condition ..> stringExpression
  Condition .d.> castToBool
  Condition .d.> BoolLiteral

'for better arrangements of the classes below Condition
' match .l[hidden]. comparison



@enduml