openapi: 3.0.3
info:
  title: DotAAS Part 2 | HTTP/REST | AASX File Server API
  description: The AASX file server API as part of Details of the Asset Administration Shell Part 2
  contact:
    name: Constantin Ziesche, Andreas Orzelski, Florian Krebs, Bastian Rössl, Manuel Sauer, Jens Vialkowitsch, Michael Hoffmeister, Torben Miny, Sebastian Bader, Marko Ristin, Nico Braunisch
  version: V1.0RC03
  termsOfService: https://github.com/admin-shell-io/aas-specs
servers:
- url: '{protocol}://{host_name}:{port}/api/{version_prefix}'
  variables:
    protocol:
      description: 'Allows access through http and https (recommended)'
      enum:
        - 'http'
        - 'https'
      default: 'https'
    host_name:
      default: admin-shell.io
      description: 'Hostname of server hosting the api'
    port:
      enum:
        - '80'
        - '443'
      default: '443'
      description: '80 is default for http, 443 for https'
    version_prefix:
      enum:
        - 'v1'
      default: v1
paths:
  /packages:
    get:
      tags:
        - AASX File Server API
      summary: Returns a list of available AASX packages at the server
      operationId: GetAllAASXPackageIds
      x-semanticIds:
        - https://admin-shell.io/aas/API/GetAllAASXPackageIds/1/0/RC03
      parameters:
        - name: aasId
          in: query
          description: The Asset Administration Shell’s unique id (UTF8-BASE64-URL-encoded)
          required: false
          style: form
          explode: true
          schema:
            type: string
            format: byte
      responses:
        '200':
          description: Requested package list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V1.0RC03#/components/schemas/PackageDescription'
        default:
          description: Default error handling for unmentioned status codes
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V1.0RC03#/components/schemas/Result'
    post:
      tags:
        - AASX File Server API
      summary: Stores the AASX package at the server
      operationId: PostAASXPackage
      x-semanticIds:
        - https://admin-shell.io/aas/API/PostAASXPackage/1/0/RC03
      requestBody:
        description: AASX package
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                aasIds:
                  type: array
                  items:
                    type: string
                file:
                  type: string
                  format: binary
                fileName:
                  type: string
            encoding:
              file:
                contentType: application/asset-administration-shell-package
        required: true
      responses:
        '201':
          description: AASX package stored successfully
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V1.0RC03#/components/schemas/PackageDescription'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V1.0RC03#/components/schemas/Result'
        default:
          description: Default error handling for unmentioned status codes
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V1.0RC03#/components/schemas/Result'
  /packages/{packageId}:
    get:
      tags:
        - AASX File Server API
      summary: Returns a specific AASX package from the server
      operationId: GetAASXByPackageId
      x-semanticIds:
        - https://admin-shell.io/aas/API/GetAASXByPackageId/1/0/RC03
      parameters:
        - name: packageId
          in: path
          description: The package Id (UTF8-BASE64-URL-encoded)
          required: true
          style: simple
          explode: true
          schema:
            type: string
            format: byte
      responses:
        '200':
          description: Requested AASX package
          headers:
            X-FileName:
              schema:
                type: string
              description: Filename of the package
          content:
            application/asset-administration-shell-package:
              schema:
                type: string
                format: binary
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V1.0RC03#/components/schemas/Result'
        default:
          description: Default error handling for unmentioned status codes
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V1.0RC03#/components/schemas/Result'
    put:
      tags:
        - AASX File Server API
      summary: Updates the AASX package at the server
      operationId: PutAASXByPackageId
      x-semanticIds:
        - https://admin-shell.io/aas/API/PutAASXByPackageId/1/0/RC03
      parameters:
        - name: packageId
          in: path
          description: The Package Id (UTF8-BASE64-URL-encoded)
          required: true
          style: simple
          explode: true
          schema:
            type: string
            format: byte
      requestBody:
        description: AASX package
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                aasIds:
                  type: array
                  items:
                    type: string
                file:
                  type: string
                  format: binary
                fileName:
                  type: string
            encoding:
              file:
                contentType: application/asset-administration-shell-package
        required: true
      responses:
        '204':
          description: AASX package updated successfully
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V1.0RC03#/components/schemas/Result'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V1.0RC03#/components/schemas/Result'      
        default:
          description: Default error handling for unmentioned status codes
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V1.0RC03#/components/schemas/Result' 
    delete:
      tags:
        - AASX File Server API
      summary: Deletes a specific AASX package from the server
      operationId: DeleteAASXByPackageId
      x-semanticIds:
        - https://admin-shell.io/aas/API/DeleteAASXByPackageId/1/0/RC03
      parameters:
        - name: packageId
          in: path
          description: The Package Id (UTF8-BASE64-URL-encoded)
          required: true
          style: simple
          explode: true
          schema:
            type: string
            format: byte
      responses:
        '204':
          description: Deleted successfully
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V1.0RC03#/components/schemas/Result'      
        default:
          description: Default error handling for unmentioned status codes
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V1.0RC03#/components/schemas/Result'