openapi: 3.1.0
info:
  title: DotAAS Part 2 | HTTP/REST | Bulk Asset Administration Shell Registry Service Specification
  description: >-
    The Bulk Profile of the Asset Administration Shell Registry Service
    Specification as part of the [Specification of the Asset Administration
    Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub).  

    The server processes all requests asynchronously, ensuring atomic
    operations. This means that requested manipulations will either fully
    succeed or be completely rolled back if any error occurs during the
    process.  

    Publisher: Industrial Digital Twin Association (IDTA) 2025
  contact:
    name: Industrial Digital Twin Association (IDTA)
    email: info@idtwin.org
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  version: V3.1.0_SSP-003
  x-profile-identifier: https://admin-shell.io/aas/API/3/1/AssetAdministrationShellRegistryServiceSpecification/SSP-003
servers:
- url: 'https://admin-shell.io/api/v3.1'
- url: 'https://example.com/'

paths:
  /bulk/shell-descriptors:
    post:
      tags:
        - Async Bulk Asset Administration Shell Registry API
      summary: >-
        Creates multiple new Asset Administration Shell Descriptors, i.e.
        registers multiple Asset Administration Shells
      operationId: CreateBulkAssetAdministrationShellDescriptors
      x-semanticIds:
        - https://admin-shell.io/aas/API/CreateBulkAssetAdministrationShellDescriptors/3/1
      requestBody:
        description: List of Asset Administration Shell Descriptor objects
        content:
          application/json:
            schema:
              type: array
              minItems: 1
              items:
                $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/schemas/AssetAdministrationShellDescriptor"
        required: true
      responses:
        '202':
          $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/responses/accepted"
        '400':
          $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/responses/bad-request"
        '401':
          $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/responses/unauthorized"
        '403':
          $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/responses/forbidden"
        '500':
          $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/responses/internal-server-error"
    put:
      tags:
        - Async Bulk Asset Administration Shell Registry API
      summary: Updates multiple existing Asset Administration Shell Descriptors
      operationId: PutBulkAssetAdministrationShellDescriptorsById
      x-semanticIds:
        - https://admin-shell.io/aas/API/PutBulkAssetAdministrationShellDescriptorsById/3/1
      requestBody:
        description: List of Asset Administration Shell Descriptor objects
        content:
          application/json:
            schema:
              type: array
              minItems: 1
              items:
                $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/schemas/AssetAdministrationShellDescriptor"
        required: true
      responses:
        '202':
          $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/responses/accepted"
        '400':
          $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/responses/bad-request"
        '401':
          $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/responses/unauthorized"
        '403':
          $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/responses/forbidden"
        '500':
          $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/responses/internal-server-error"
    delete:
      tags:
        - Async Bulk Asset Administration Shell Registry API
      summary: >-
        Deletes multiple Asset Administration Shell Descriptors, i.e.
        de-registers multiple Asset Administration Shells
      operationId: DeleteBulkAssetAdministrationShellDescriptorsById
      x-semanticIds:
        - https://admin-shell.io/aas/API/DeleteBulkAssetAdministrationShellDescriptorsById/3/1
      requestBody:
        description: List of Asset Administration Shell's unique ids
        content:
          application/json:
            schema:
              type: array
              minItems: 1
              items:
                type: string
      responses:
        '202':
          $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/responses/accepted"
        '400':
          $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/responses/bad-request"
        '401':
          $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/responses/unauthorized"
        '404':
          $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/responses/not-found"
        '500':
          $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/responses/internal-server-error"
  /bulk/status/{handleId}:
    get:
      tags:
        - Async Bulk Status API
      summary: Returns the status of an asynchronously invoked bulk operation
      operationId: GetAsyncBulkStatus
      x-semanticIds:
        - https://admin-shell.io/aas/API/GetAsyncBulkStatus/3/1
      parameters:
        - in: path
          name: handleId
          schema:
            $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/parameters/HandleId"
          required: true
      responses:
        '200':
          description:   Bulk operation result object containing information that the
            'executionState' is still 'Running'
          headers:
            Retry-After:
              schema:
                type: integer
              required: false
              description: The number of seconds to wait before retrying the request.
          content:
            application/json:
              schema:
                $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/schemas/BaseOperationResult"
        '302':
          $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/responses/found"
        '401':
          $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/responses/unauthorized"
        '403':
          $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/responses/forbidden"
        '404':
          $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/responses/not-found"
        '500':
          $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/responses/internal-server-error"
  /bulk/result/{handleId}:
    get:
      tags:
        - Async Bulk Result API
      summary: Returns the result object of an asynchronously invoked bulk operation
      operationId: GetBulkAsyncResult
      x-semanticIds:
        - https://admin-shell.io/aas/API/GetBulkAsyncResult/3/1
      parameters:
        - in: path
          name: handleId
          schema:
            $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/parameters/HandleId"
          required: true
      responses:
        '204':
          description:   The bulk request itself was correct and all elements have been
            processed. The server may remove the result resource after  it was
            requested once (by any client) or after a certain time period.
        '400':
          description:   There was an error in the processing of the request. Either the bulk
            request itself was not correct, or at least of it's part requests. 
            The whole transaction has been rolled back.
          $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/responses/bad-request"
        '401':
          $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/responses/unauthorized"
        '403':
          $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/responses/forbidden"
        '404':
          description:   The handleId is not known to the server. This means either it never
            came into existence or it was successfully completed a considerable
            time in the past.
          $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/responses/not-found"
        '500':
          $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/responses/internal-server-error"
  /description:
    get:
      tags:
        - Description API
      summary: >-
        Returns the self-describing information of a network resource
        (ServiceDescription)
      operationId: GetDescription
      x-semanticIds:
        - https://admin-shell.io/aas/API/Descriptor/GetDescription/3/0
      responses:
        '200':
          description: Requested Description
          content:
            application/json:
              schema:
                $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/schemas/ServiceDescription"
        '403':
          $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/responses/forbidden"
        default:
          $ref: "https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.1.0#/components/responses/default"
