////
Copyright (c) 2023 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/). 

SPDX-License-Identifier: CC-BY-4.0

////

include::../includes/special-parameters.adoc[]



= Basic Operation Parameters

== General

This clause specifies the parameters for API operations.

[#SerializationModifier]
== SerializationModifiers in Operations

=== Definition

For GET operations, a SerializationModifier indicates the requester’s expected or desired response content.
For PUT and PATCH operations, a SerializationModifier indicates the input content.
The SerializationModifier comprises three orthogonal enumerations.
When combined, these enumerations influence the input or response content of the requested operation.

====
Note: values remain unchanged with content=metadata.
====


=== Enumeration: Level

The first enumeration _Level_ indicates the depth of the structure of the response or input content.

.Level Parameters
[%autowidth,width="100%",cols="35%,65%",options="header",]
|===
h|Value h|Explanation
e|Deep (Default) a|
All elements of a requested hierarchy level and all children on all sublevels are returned.
Children in this sense are SubmodelElements which are contained at the ‘submodelElements’ field of Submodels, the ‘value’ field of SubmodelElementCollections or SubmodelElementLists, the ‘statements’ field of Entities, or the ‘annotations’ field of AnnotatedRelationshipElements.
e|Core a|
Only elements of a requested hierarchy level as well as direct children are returned.
By this, a client can iterate the hierarchy step by step.
|===

====
Note: level parameters are mapped to the query parameter "?level" in the HTTP/REST APIs, see also xref:http-rest-api/http-rest-api.adoc#modifier-constraints[Modifier Constraints].
====


=== Enumeration: Content

The second enumeration _Content_ indicates the kind of serialization of the response or input content.

For Content equal to Normal see Clause link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/mappings/mappings.html#_format_normal_in_xml[] and link:https://https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/mappings/mappings.html#_format_normal_in_json[]  in Part 1 for details. 
It is defined for XML and JSON only.

For Content equal to Metadata see Clause link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/mappings/mappings.html#_format_metadata_metadata_serialization[] in Part 1 for details.

For Content equal to Value see Clause link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/mappings/mappings.html#value-only-serialization-in-json[] in Part 1 for details. 
It is defined for JSON only.

For Content equal to Reference see Clause link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/mappings/mappings.html#_format_reference[] in Part 1 for details.

For Content equal to Path see Clause link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/mappings/mappings.html#_format_path_idshortpath_serialization_in_json[] in Part 1 for details.

.Content Parameters
[%autowidth,width="100%",cols="35%,65%",options="header",]
|===
h|Value h|Explanation
e|Normal (Default) a|The standard serialization of the model element or child elements is applied.
e|Metadata a|Only metadata of an element or child elements is returned; the value is not .
e|Value a|Only the raw value of the model element or child elements is returned; it is commonly referred to as _ValueOnly_-serialization.
e|Reference a|Only applicable to Referables. Only the reference to the found element is returned; potential child elements are ignored.
e|Path a|Returns the idShort of the requested element and a list of _idShort_ paths to child elements if the requested element is a Submodel, a SubmodelElementCollection, a SubmodelElementList, a AnnotatedRelationshipElement, or an Entity.
|===

====
Note: level parameters are mapped to path suffixes "/$<content>" in the HTTP/REST APIs, see also xref:http-rest-api/http-rest-api.adoc#modifier-constraints[Modifier Constraints].
====


=== Enumeration: Extent

The third enumeration _Extent_ indicates to which extent the response or input content is being serialized.
At this stage, the listed values could also be represented as binary values on BLOB-elements.
They are, however, kept as generic extent values for the sake of extension.

.Extent Parameters
[%autowidth,width="100%",cols="35%,65%",options="header",]
|===
h|Value h|Explanation
e|WithoutBLOBValue (Default) |Only applicable to BLOB-elements; the BLOB content is not returned.
e|WithBLOBValue |Only applicable to BLOB-elements; the BLOB content is returned as _base64_-encoded string.
|===

====
Note: level parameters are mapped to the query parameter "?extent" in the HTTP/REST APIs, see also xref:http-rest-api/http-rest-api.adoc#modifier-constraints[Modifier Constraints].
====

== Applicability of SerializationModifiers

The defined SerializationModifiers are only valid for specific operations due to their generic nature.
Also, the applicability depends on the kind of the accessed resource.
The following list defines the applicability of the modifiers to the resources.

GET and PATCH operations may combine all SerializationModifiers as listed below.
PUT operations may only use the Extent Modifier.
POST operations do not use SerializationModifiers.

.Applicability of SerializationModifiers
[%autowidth,width="100%",cols="37%,13%,28%,22%",options="header",]
|===
h|Resource Name h|Level Modifier h|Content Modifier h|Extent Modifier
|Asset Administration Shell |No |Normal/ Reference |No
|Submodel Reference |No |No |No
|Submodel |Deep/Core |Normal/ Metadata/ Value/ Reference/ Path a|
WithoutBLOBValue/

WithBLOBValue

4+|*SubmodelElements*
|SubmodelElementCollection |Deep/Core |Normal/ Metadata/ Value/ Reference/ Path a|
WithoutBLOBValue/

WithBLOBValue

|SubmodelElementList |Deep/Core |Normal/ Metadata/ Value/ Reference/ Path a|
WithoutBLOBValue/

WithBLOBValue

|Entity |Deep/Core |Normal/ Metadata/ Value/ Reference/ Path a|
WithoutBLOBValue/

WithBLOBValue

|BasicEventElement |No |Normal/ Metadata/ Value/ Reference |No
|Capability |No |Normal/Reference |No
|Operation |No |Normal/Reference |No
4+|*DataElements*
|Property |No |Normal/ Metadata/ Value/ Reference |No
|MultiLanguageProperty |No |Normal/ Metadata/ Value/ Reference |No
|Range |No |Normal/ Metadata/ Value/ Reference |No
|ReferenceElement |No |Normal/ Metadata/ Value/ Reference |No
|RelationshipElement |No |Normal/ Metadata/ Value/ Reference |No
|AnnotatedRelationshipElement |No |Normal/ Metadata/ Value/ Reference |No
|Blob |No |Normal/ Metadata/ Value/ Reference a|
WithoutBLOBValue/

WithBLOBValue

|File |No |Normal/ Metadata/ Value/ Reference |No
|===

====
Note: EventPayload defines the necessary information of an event instance sent out or received.
It is, however not part of the AAS and submodel hierarchical structure.
====

