////
Copyright (c) 2023 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/). 

SPDX-License-Identifier: CC-BY-4.0

////

include::../includes/special-parameters.adoc[]


[#aas-interfaces]
== Asset Administration Shell Interfaces

=== General

These interfaces make it possible to access the elements of Asset Administration Shells or Submodels.

The AASX File Server Interface enables management of AASX packages on a server.
A list of available packages can be retrieved.
Each package in the list can be downloaded, uploaded, or deleted.
New packages can also be added.

AASX packages are stored and managed independently of instantiated Asset Administration Shells or submodels on a server.
The server documentation shall contain a description of when and how AASX packages are handled, e.g. if Asset Administration Shells or Submodels in AASX packages are instantiated at startup of the server and/or if they are also instantiated when an AASX package is changed by an API operation.

=== Asset Administration Shell Interface and Operations

==== Asset Administration Shell Interface

[%autowidth,width="100%",options=header]
|===
2+h|Interface: _Asset Administration Shell_
h|Operation Name h|Description
e|GetAssetAdministrationShell a|Returns the Asset Administration Shell
e|PutAssetAdministrationShell a|Replaces the current Asset Administration Shell
e|GetAllSubmodelReferences a|Returns all Submodel References
e|PostSubmodelReference a|Creates a Submodel Reference at the Asset Administration Shell
e|DeleteSubmodelReference a|Deletes a specific Submodel Reference from the Asset Administration Shell
e|GetAssetInformation a|Returns the Asset Information
e|PutAssetInformation a|Replaces the Asset Information
e|GetThumbnail a|Returns the thumbnail file
e|PutThumbnail a|Replaces the thumbnail file
e|DeleteThumbnail a|Deletes the thumbnail
|===

==== Operation GetAssetAdministrationShell

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[GetAssetAdministrationShell]]GetAssetAdministrationShell
h|Explanation 4+a|Returns the Asset Administration Shell
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetAssetAdministrationShell/3/0`

h|Name h|Description h|Mand. h|Type h|Card.

5+h|Input Parameter
e|serializationModifier a|Defines the format of the response |no |xref:specification/interfaces-operation-parameters.adoc#SerializationModifier[SerializationModifier] |1
5+h|Output Parameter
e|statusCode a|Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
e|payload a|Requested Asset Administration Shell |yes | link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/core.html#AssetAdministrationShell[AssetAdministrationShell] |1
|===

==== Operation PutAssetAdministrationShell

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|*Operation Name* 4+e|[[PutAssetAdministrationShell]]PutAssetAdministrationShell
hh|Explanation 4+a|Replaces the Asset Administration Shell
h|*semanticId* 4+|`\https://admin-shell.io/aas/API/PutAssetAdministrationShell/3/0`

h|Name h|*Description* h|*Mand.* h|*Type* h|*Card.*
5+h|Input Parameter
e|aas a|AssetAdministrationShell |yes |link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/core.html#AssetAdministrationShell[AssetAdministrationShell] object |1
5+h|Output Parameter
e|statusCode a|StatusCode |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode]  |1
e|payload a|AssetAdministrationShell |no |Replaced link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/core.html#AssetAdministrationShell[AssetAdministrationShell] |1
|===

==== Operation GetAllSubmodelReferences

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[GetAllSubmodelReferences]]GetAllSubmodelReferences
h|Explanation 4+a|Returns all Submodel References
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetAllSubmodelReferences/3/0`

h|Name h|Description h|Mand. h|Type h|Card.

5+h|Input Parameter
e|limit a|The maximum size of the result set |no |nonNegativeInteger |1
e|cursor a|The position from which to resume a result listing |no |string |1

5+h|Output Parameter
e|statusCode a|Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
e|payload a|Requested Submodel References |yes |link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/referencing.html#Reference[Reference]  |0..*
|===

==== Operation PostSubmodelReference

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[PostSubmodelReference]]PostSubmodelReference
h|Explanation 4+a|Creates a Submodel Reference at the Asset Administration Shell
h|semanticId 4+|`\https://admin-shell.io/aas/API/PostSubmodelReference/3/0`

h|Name h| Description h|Mand. h|Type h|Card.
5+h|Input Parameter
e|submodelRef | Reference to the Submodel |yes |link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/referencing.html#Reference[Reference]  |1
5+h|Output Parameter
e|statusCode | Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
e|payload | Created Submodel Reference |yes |link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/referencing.html#Reference[Reference]  |1
|===

==== Operation DeleteSubmodelReference

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[DeleteSubmodelReference]]DeleteSubmodelReference
h|Explanation 4+a|Deletes the Submodel Reference from the Asset Administration Shell
h|semanticId 4+|`\https://admin-shell.io/aas/API/DeleteSubmodelReference/3/0`

h|Name h| Description h|Mand. h|Type h|Card.
5+h|Input Parameter
e|submodelId | The unique id of the Submodel for the reference to be deleted |yes |link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/datatypes.html#Identifier[Identifier] |1
5+h|Output Parameter
e|statusCode | Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|===

==== Operation GetAssetInformation

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[GetAssetInformation]]GetAssetInformation
h|Explanation 4+a|Returns the Asset Information
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetAssetInformation/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
5+h|Output Parameter
e|statusCode a|Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
e|payload a|Requested Asset Information |yes |link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/core.html#AssetInformation[AssetInformation] |1
|===

==== Operation PutAssetInformation

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|*Operation Name* 4+e|[[PutAssetInformation]]PutAssetInformation
h|Explanation 4+a|Replaces the Asset Information
h|semanticId 4+|`\https://admin-shell.io/aas/API/PutAssetInformation/3/0`

h|Name h|Description h|Mand. h|Type h|Card.

5+h|Input Parameter

e|assetInfo a|Asset Information object |yes |link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/core.html#AssetInformation[AssetInformation] |1

5+h|Output Parameter

e|statusCode a|Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|===

==== Operation GetThumbnail

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[GetThumbnail]]GetThumbnail
h|Explanation 4+a|Returns the thumbnail file
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetThumbnail/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
5+h|Output Parameter
e|statusCode a|Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
e|payload a|Requested thumbnail file |yes |File Content |1
|===

==== Operation PutThumbnail

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[PutThumbnail]]PutThumbnail
h|Explanation 4+a|Replaces the thumbnail file
h|semanticId 4+|`\https://admin-shell.io/aas/API/PutThumbnail/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
e|file a|Thumbnail file |yes |File Content |1
5+h|Output Parameter
e|statusCode a|Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|===

==== Operation DeleteThumbnail

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[DeleteThumbnail]]DeleteThumbnail
h|Explanation 4+a|Deletes the thumbnail file
h|semanticId 4+|`\https://admin-shell.io/aas/API/DeleteThumbnail/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
5+h|Output Parameter
e|statusCode a|Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|===

=== Submodel Interface and Operations

==== Submodel Interface

[%autowidth,width="100%",cols="42%,58%",options="header",]
|===
2+|Interface: [[Submodel]]Submodel
h|Operation Name h|Description

e|GetSubmodel a|Returns the Submodel
e|GetAllSubmodelElements a|Returns all submodel elements including their hierarchy
e|GetSubmodelElementByPath a|Returns a specific submodel element from the Submodel at a specified path
e|GetFileByPath a|Returns a specific file from the Submodel at a specified path
e|PutFileByPath a|Replaces the file of an existing submodel element at a specified path within the submodel element hierarchy
e|DeleteFileByPath a|Deletes the file of an existing submodel element at a specified path within the submodel element hierarchy
e|PutSubmodel a|Replaces the Submodel
e|PatchSubmodel a|Updates the Submodel
e|PostSubmodelElement a|Creates a new submodel element as a child of the submodel. The idShort of the new submodel element must be set in the payload.
e|PostSubmodelElementByPath a|Creates a new submodel element at a specified path within the submodel elements hierarchy. The idShort of the new submodel element must be set in the payload.
e|PutSubmodelElementByPath a|Replaces an existing submodel element at a specified path within the submodel element hierarchy
e|PatchSubmodelElementByPath a|Updates an existing submodel element at a specified path within the submodel element hierarchy
e|GetSubmodelElementValueByPath a|Returns the value of the submodel element at a specified path according to the protocol-specific RAW-value payload
e|DeleteSubmodelElementByPath a|Deletes a submodel element at a specified path within submodel element hierarchy
e|InvokeOperationSync a|Synchronously invokes an Operation at a specified path with a client timeout in ms
e|InvokeOperationAsync a|Asynchronously invokes an Operation at a specified path with a client timeout in ms
e|GetOperationAsyncStatus a|Returns the current status of an asynchronously invoked operation
e|GetOperationAsyncResult a|Returns the OperationResult of an asynchronously invoked operation
|===

==== Operation GetSubmodel

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[GetSubmodel]]GetSubmodel
h|Explanation 4+a|Returns the Submodel
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetSubmodel/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|serializationModifier |Defines the format of the response |no |xref:specification/interfaces-operation-parameters.adoc#SerializationModifier[SerializationModifier]  |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Requested Submodel |yes |link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/core.html#Submodel[Submodel] |1
|===

==== Operation GetAllSubmodelElements

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[GetAllSubmodelElements]]GetAllSubmodelElements
h|Explanation 4+a|Returns all submodel elements including their hierarchy
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetAllSubmodelElements/3/0

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|serializationModifier |Defines the format of the response |no |xref:specification/interfaces-operation-parameters.adoc#SerializationModifier[SerializationModifier]  |1
|limit |The maximum size of the result set |no |nonNegativeInteger |1
|cursor |The position from which to resume a result listing |no |string |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Requested submodel elements |yes |link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/core.html#SubmodelElement[SubmodelElement] |0..*
|===

==== Operation GetSubmodelElementByPath

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[GetSubmodelElementByPath]]GetSubmodelElementByPath
h|Explanation 4+a|Returns a specific submodel element from the Submodel at a specified path
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetSubmodelElementByPath/3/0

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|path | {path} |yes |Key |1..*
|serializationModifier |Defines the format of the response |no |xref:specification/interfaces-operation-parameters.adoc#SerializationModifier[SerializationModifier]  |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Requested submodel element |yes |link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/core.html#SubmodelElement[SubmodelElement] |0..1
|===

==== Operation GetFileByPath

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[GetFileByPath]]GetFileByPath
h|Explanation 4+a|Returns a specific file from the Submodel at a specified path
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetFileByPath/3/0

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|path |{path} |yes |Key |1..*
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Requested file |yes |File Content |0..1
|===

==== Operation PutFileByPath

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[PutFileByPath]]PutFileByPath
h|Explanation 4+a|Replaces the file of an existing submodel element at a specified path within the submodel element hierarchy
h|semanticId 4+|`\https://admin-shell.io/aas/API/PutFileByPath/3/0

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|path |{path} |yes |Key |1..*
|payload |Replacing file |yes |File Content |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|===

==== Operation DeleteFileByPath

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[DeleteFileByPath]]DeleteFileByPath
h|Explanation 4+a|Deletes the file of an existing submodel element at a specified path within the submodel element hierarchy
h|semanticId 4+|`\https://admin-shell.io/aas/API/DeleteFileByPath/3/0

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|path |idShortPath via relative Reference/Keys to a submodel element |yes |Key |1..*
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|===

==== Operation PutSubmodel

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[PutSubmodel]]PutSubmodel
h|Explanation 4+a|Replaces the Submodel
h|semanticId 4+|`\https://admin-shell.io/aas/API/PutSubmodel/3/0

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|submodel |Submodel object |yes |Submodel |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Replaced submodel |yes |Submodel |1
|===

==== Operation PatchSubmodel

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[PatchSubmodel]]PatchSubmodel
h|Explanation 4+a|Updates the Submodel
h|semanticId 4+|`\https://admin-shell.io/aas/API/PatchSubmodel/3/0

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|serializationModifier a|
Defines the format of the input


====
Note: values remain unchanged with content=metadata.
====


|no |xref:specification/interfaces-operation-parameters.adoc#SerializationModifier[SerializationModifier]  |1
|submodel |Submodel object |yes |Submodel |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Updated submodel |no |Submodel |1
|===

==== Operation PostSubmodelElement

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[PostSubmodelElement]]PostSubmodelElement
h|Explanation 4+a|
Creates a new submodel element as a child of the submodel.
The idShort of the new submodel element must be set in the payload.


====
Note: the creation of the idShort is out of scope and must be handled in a proprietary way.
====


h|semanticId 4+|`\https://admin-shell.io/aas/API/PostSubmodelElement/3/0`

h|Name h|Description h|Mand. h|Type h|Card.

5+h|Input Parameter

|submodelElement |Submodel element object |yes |SubmodelElement |

5+h|Output Parameter

|StatusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode]|1
|payload |Created submodel element |yes |link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/core.html#SubmodelElement[SubmodelElement] |1
|===

==== Operation PostSubmodelElementByPath

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[PostSubmodelElementByPath]]PostSubmodelElementByPath
h|Explanation 4+a|
Creates a new submodel element at a specified path within the submodel element hierarchy.
The idShort of the new submodel element must be set in the payload.


====
Note: the creation of the idShort is out of scope and must be handled in a proprietary way.
====


h|semanticId 4+|`\https://admin-shell.io/aas/API/PostSubmodelElementByPath/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|path |{path} under which the new SubmodelElement shall be added |yes |Key |1..*
|submodelElement |Submodel element object |yes |link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/core.html#SubmodelElement[SubmodelElement] |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Created submodel element |yes |link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/core.html#SubmodelElement[SubmodelElement] |1
|===

====
Note: if the PostSubmodelElementByPath is executed towards a SubmodelElementList, the new SubmodelElement is added to the end of the list.
====

==== Operation PutSubmodelElementByPath

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[PutSubmodelElementByPath]]PutSubmodelElementByPath
h|Explanation 4+a|Replaces an existing submodel element at a specified path within the submodel element hierarchy
h|semanticId 4+|`\https://admin-shell.io/aas/API/PutSubmodelElementByPath/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|path |{path} which shall be replaced |yes |Key |1..*
|submodelElement |Submodel element object |yes |link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/core.html#SubmodelElement[SubmodelElement] |1
5+h|Output Parameter
|StatusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Replaced submodel element | no |link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/core.html#SubmodelElement[SubmodelElement] |1
|===

==== Operation PatchSubmodelElementByPath

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[PatchSubmodelElementByPath]]PatchSubmodelElementByPath
h|Explanation 4+a|Updates an existing submodel element at a specified path within the submodel element hierarchy
h|semanticId 4+|`\https://admin-shell.io/aas/API/PatchSubmodelElementByPath/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|serializationModifier a|
Defines the format of the input


====
Note: values remain unchanged with content=metadata.
====


|no |xref:specification/interfaces-operation-parameters.adoc#SerializationModifier[SerializationModifier] |1

|path |{path} |yes |Key |1..*
|submodelElement |Submodel element object |yes |link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/core.html#SubmodelElement[SubmodelElement] |1

5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1

|payload |Updated submodel element | no |link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/core.html#SubmodelElement[SubmodelElement] |1
|===

==== Operation GetSubmodelElementValueByPath

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[GetSubmodelElementValueByPath]]GetSubmodelElementValueByPath
h|Explanation 4+a|Returns a specific submodel element value from the Submodel at a specified path according to the ValueOnly-serialization as defined in clause 11.4.1
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetSubmodelElementValueByPath/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|path |{path} |yes  |Key |1..*
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Requested submodel element value |yes |link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/core.html#SubmodelElement[SubmodelElement] |1
|===

==== Operation PatchSubmodelElementValueByPath

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[PatchSubmodelElementValueByPath]]PatchSubmodelElementValueByPath
h|Explanation 4+a|Sets the value of the submodel element at a specified path according to the ValueOnly-serialization as defined in clause 11.4.1
h|semanticId 4+|`\https://admin-shell.io/aas/API/PatchSubmodelElementValueByPath/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|path |{path} |yes |Key |1..*
|payload |The new value of the submodel element |yes |link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/core.html#SubmodelElement[SubmodelElement] |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|===

==== Operation DeleteSubmodelElementByPath

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[DeleteSubmodelElementByPath]]DeleteSubmodelElementByPath
h|Explanation 4+a|Deletes a submodel element at a specified path within the submodel elements hierarchy
h|semanticId 4+|`\https://admin-shell.io/aas/API/DeleteSubmodelElementByPath/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|path |{path} |yes |Key |1..*
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|===

==== Operation InvokeOperationSync

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[InvokeOperationSync]]InvokeOperationSync
h|Explanation 4+a|Synchronously invokes an Operation at a specified path
h|semanticId 4+|`\https://admin-shell.io/aas/API/InvokeOperationSync/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|path |{path}, in this case an operation |yes |Key |1..*
|inputArgument |Input argument |no |link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/submodel-elements.html#OperationVariable[OperationVariable] |1..*
|inoutputArgument |Inoutput argument |no |link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/submodel-elements.html#OperationVariable[OperationVariable] |1..*
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |The Operation Result |yes |xref:OperationResult[OperationResult] |1
|===

==== Operation InvokeOperationAsync

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[InvokeOperationAsync]]InvokeOperationAsync
h|Explanation 4+a|Asynchronously invokes an Operation at a specified path
h|semanticId 4+|`\https://admin-shell.io/aas/API/InvokeOperationAsync/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|path |{path}, in this case an operation |yes |Key |1..*
|inputArgument |Input argument |no |link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/submodel-elements.html#OperationVariable[OperationVariable] |1..*
|inoutputArgument |Inoutput argument |no |link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/submodel-elements.html#OperationVariable[OperationVariable] |1..*
|clientTimeoutDuration |Timestamp indicating when the client expects the server to have finished execution of the invoked operation |yes |duration |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |The returned handle of an operation’s asynchronous invocation used to request the current state of the operation’s execution |yes |OperationHandle |1
|===

==== Operation GetOperationAsyncStatus

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[GetOperationAsyncStatus]]GetOperationAsyncStatus
h|Explanation 4+a|Returns the current status of an asynchronously invoked operation
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetOperationAsnycStatus/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|operationHandle |The returned handle of an operation’s asynchronous invocation used to request the current state of the operation’s execution |yes |xref:OperationHandle[OperationHandle] |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Execution state of the operation |yes | xref:BaseOperationResult[BaseOperationResult] |1
|===

==== Operation GetOperationAsyncResult

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[GetOperationAsyncResult]]GetOperationAsyncResult
h|Explanation 4+a|Returns the OperationResult of an asynchronously invoked operation
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetOperationAsnycResult/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|operationHandle |The returned handle of an operation’s asynchronous invocation used to request the current state of the operation’s execution |yes |OperationHandle |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Operation Result |yes |xref:OperationResult[OperationResult] |1
|===

=== Serialization Interface and Operations

==== Serialization Interface

[%autowidth,width="100%",cols="27%,73%",options="header",]
|===
2+|Interface: [[Serialization]]Serialization
h|Operation Name h|[[Description]]Description
|GenerateSerializationByIds |Returns an appropriate serialization based on the specified format (see SerializationFormat).
|===

==== Operation GenerateSerializationByIds

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[GenerateSerializationByIds]]GenerateSerializationByIds
h|Explanation 4+a|Returns an appropriate serialization based on the specified format (see SerializationFormat).
h|semanticId 4+|`\https://admin-shell.io/aas/API/GenerateSerializationByIds/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|aasIds |The unique ids of the Asset Administration Shells to be contained in the serialization |no |Identifier |1..*
|submodelIds |The unique ids of the Submodels to be contained in the serialization |no |Identifier |1..*
|includeConceptDescriptions |Include concept descriptions |no |boolean |1
|serializationFormat |Denotes in which serialization format the requested content shall be delivered |no |SerializationFormat |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Serialization of the requested Asset Administration Shells and/or Submodels with or without ConceptDescriptions in specified SerializationFormat. |yes |link:https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/environment.html#Environment[Environment] |1
|===

[.table-with-appendix-table]
[cols="30%h,70%"]
|===

h|Enumeration: e|[[SerializationFormat]]SerializationFormat
h|Explanation: a|Determines the format of serialization, i.e. JSON, XML, RDF, AML, etc.RFC 6838, IANA Media Types, and defined custom content types; additional elements may be added in future versions
h|Set of: |--
h|Literal h|Explanation
e|application/json a|JSON serialization of the requested data object inside an AAS Environment structure
e|application/xml a|XML serialization of the requested data object inside an AAS Environment structure (default)
e|application/asset-administration-shell-package+xml a|AASX-Package (binary data) containing the requested data object
|===

=== AASX File Server Interface and Operations

==== AASX File Server Interface

[%autowidth,width="100%",cols="33%,67%",options="header",]
|===
2+|Interface: [[AASX-File-Server]]AASX File Server
h|Operation Name h|Description
e|GetAllAASXPackageIds |Returns a list of available AASX packages at the server
e|GetAASXByPackageId |Returns a specific AASX package from the server
e|PostAASXPackage |Creates an AASX package at the server
e|PutAASXByPackageId |Replaces the AASX package at the server
e|DeleteAASXByPackageId |Deletes a specific AASX package
|===

==== Operation GetAllAASXPackageIds

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[GetAllAASXPackageIds]]GetAllAASXPackageIds
h|Explanation 4+a|Returns a list of available AASX packages at the server
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetAllAASXPackageIds/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|aasId |Identifier of the AAS which must exist in each matching AASX package |no |Identifier |1
|limit |The maximum size of the result set |no |nonNegativeInteger |1
|cursor |The position from which to resume a result listing |no |string |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Matching package list; the PackageDescription includes all Asset Administration Shell identifiers, also those which may have not been requested through the aasId input parameter |yes |PackageDescription |0..*
|===

==== Operation GetAASXByPackageId

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[GetAASXByPackageId]]GetAASXByPackageId
h|Explanation 4+a|Returns a specific AASX package from the server
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetAASXByPackageId/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|packageId |Requested package ID from the package list |yes |string |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|filename |Filename of the AASX package |yes |string |1
|payload |Requested AASX package |yes |AASX Package |1
|===

==== Operation PostAASXPackage

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[PostAASXPackage]]PostAASXPackage
h|Explanation 4+a|Creates an AASX package at the server
h|semanticId 4+|`\https://admin-shell.io/aas/API/PostAASXPackage/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|aasIds a|
Included AAS Ids


====
Note: it is not mandatory for servers to read and parse AASX packages.
Servers may simply store the AASX files with their related given aasIds.
====


|no |Identifier |0..*
|file |New AASX package |yes |AASX package |1
|filename |Filename of the AASX package |yes |string |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|packageId |New Package ID |yes |string |1
|===

==== Operation PutAASXPackageById

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[PutAASXPackageById]]PutAASXPackageById
h|Explanation 4+a|Replaces the AASX package at the server
h|semanticId 4+|`\https://admin-shell.io/aas/API/PutAASXPackageById/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|packageId |Package ID from the package list |yes |string |1
|aasIds a|
Included AAS Ids


====
Note: it is not mandatory for servers to read and parse AASX packages.
Servers may simply store the AASX files with their related given aasIds.
====


|no |Identifier |0..*
|file |New AASX package |yes |AASX package |1
|filename |Filename of the AASX package |yes |string |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|===

==== Operation DeleteAASXPackageById

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[DeleteAASXPackageById]]DeleteAASXPackageById
h|Explanation 4+a|Deletes a specific AASX package from the server
h|semanticId 4+|`\https://admin-shell.io/aas/API/DeleteAASXPackageById/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|packageId |Package ID from the package list |yes |string |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|===

[#registration-interfaces]
== Registration Interfaces

=== General

These interfaces allow to register and unregister descriptors of administration shells or submodels.
The descriptors contain the information needed to access the interfaces (as described in <<aas-interfaces>>) of the corresponding element.
This required information includes the endpoint in the dedicated environment.

Lookup interfaces provide access to the registered descriptors by identifiers (Asset Administration Shell and Submodel ID).
These identifiers may be discovered through the interfaces described in <<publish-and-discovery-interfaces>>.

=== Asset Administration Shell Registry Interface and Operations

==== Asset Administration Shell Registry Interface

[%autowidth,width="100%",cols="45%,55%",options="header",]
|===
2+|Interface: Asset Administration Shell Registry
h|Operation Name h|Description
|GetAllAssetAdministrationShellDescriptors a|Returns all Asset Administration Shell Descriptors
|GetAssetAdministrationShellDescriptorById a|Returns a specific Asset Administration Shell Descriptor
|PostAssetAdministrationShellDescriptor a|Creates a new Asset Administration Shell Descriptor, i.e., registers an AAS
| CreateBulkAssetAdministrationShellDescriptors a| Creates multiple new Asset Administration Shell Descriptors, i.e., registers multiple Asset Administration Shells
|PutAssetAdministrationShellDescriptorById a|Replaces an existing Asset Administration Shell Descriptor, i.e., replaces registration information
| PutBulkAssetAdministrationShellDescriptorsById a| Updates multiple existing Asset Administration Shell Descriptors
|DeleteAssetAdministrationShellDescriptorById a|Deletes an Asset Administration Shell Descriptor, i.e., de-registers an AAS
| DeleteBulkAssetAdministrationShellDescriptorsById a| Deletes multiple Asset Administration Shell Descriptors, i.e., de-registers multiple Asset Administration Shells
| QueryAssetAdministrationShellDescriptors a| Returns all Asset Administration Shell Descriptors that conform to a certain input query.
|===

==== Operation GetAllAssetAdministrationShellDescriptors

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|GetAllAssetAdministrationShellDescriptors
h|Explanation 4+a|Returns all Asset Administration Shell Descriptors
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetAllAssetAdministrationShellDescriptors/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|limit |The maximum size of the result set |no |nonNegativeInteger |1
|cursor |The position from which to resume a result listing |no |string |1
|assetKind |The kind of the assets to retrieve (Type, Instance) | no |AssetKind |1
|assetType |The type of the assets to retrieve, encoded as unique id | no |Identifier |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |List of Asset Administration Shell Descriptors |no | xref:specification/interfaces-payload.adoc#AssetAdministrationShellDescriptor[AssetAdministrationShellDescriptor]  |1..*
|===

==== Operation GetAssetAdministrationShellDescriptorById

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|GetAssetAdministrationShellDescriptorById
h|Explanation 4+a|Returns a specific Asset Administration Shell Descriptor
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetAssetAdministrationShellDescriptorById/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|aasIdentifier |The Asset Administration Shell’s unique id |yes |Identifier |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode]|1
|payload |Requested Asset Administration Shell Descriptor |yes | xref:specification/interfaces-payload.adoc#AssetAdministrationShellDescriptor[AssetAdministrationShellDescriptor]  |1
|===

==== Operation PostAssetAdministrationShellDescriptor

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|PostAssetAdministrationShellDescriptor
h|Explanation 4+a|Creates a new Asset Administration Shell Descriptor, i.e., registers an AAS
h|semanticId 4+|`\https://admin-shell.io/aas/API/PostAssetAdministrationShellDescriptor/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|shellDescriptor |Object containing the Asset Administration Shell’s identification and endpoint information  |yes | xref:specification/interfaces-payload.adoc#AssetAdministrationShellDescriptor[AssetAdministrationShellDescriptor]  |1
5+h|Output Parameter
|StatusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Created Asset Administration Shell Descriptor |yes | xref:specification/interfaces-payload.adoc#AssetAdministrationShellDescriptor[AssetAdministrationShellDescriptor]  |1
|===

==== Operation CreateBulkAssetAdministrationShellDescriptors

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[CreateBulkAssetAdministrationShellDescriptors]]CreateBulkAssetAdministrationShellDescriptors
h|Explanation 4+a|Creates multiple new Asset Administration Shell Descriptors, i.e., registers multiple Asset Administration Shells
h|semanticId 4+|`\https://admin-shell.io/aas/API/CreateBulkAssetAdministrationShellDescriptors/3/1`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|shellDescriptors |List of Asset Administration Shell Descriptor objects |yes | xref:specification/interfaces-payload.adoc#AssetAdministrationShellDescriptor[AssetAdministrationShellDescriptor] |1..*
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|===

==== Operation PutAssetAdministrationShellDescriptorById

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[PutAssetAdministrationShellDescriptorById]]PutAssetAdministrationShellDescriptorById
h|Explanation 4+a|Replaces an existing Asset Administration Shell Descriptor, i.e., replaces registration information
h|semanticId 4+|`\https://admin-shell.io/aas/API/PutAssetAdministrationShellDescriptorById/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|shellDescriptor |Object containing the Asset Administration Shell’s identification and endpoint information containing the Asset Administration Shell’s identification and endpoint information |yes | xref:specification/interfaces-payload.adoc#AssetAdministrationShellDescriptor[AssetAdministrationShellDescriptor]  |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Replaced Asset Administration Shell Descriptor |yes | xref:specification/interfaces-payload.adoc#AssetAdministrationShellDescriptor[AssetAdministrationShellDescriptor]  |1
|===

==== Operation PutBulkAssetAdministrationShellDescriptorsById

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===

h|Operation Name 4+e|[[PutBulkAssetAdministrationShellDescriptorsById]]PutBulkAssetAdministrationShellDescriptorsById
h|Explanation 4+a|Updates multiple existing Asset Administration Shell Descriptors 
h|semanticId 4+|`\https://admin-shell.io/aas/API/PutBulkAssetAdministrationShellDescriptorsById/3/1`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|shellDescriptors |List of Asset Administration Shell Descriptor objects |yes | xref:specification/interfaces-payload.adoc#AssetAdministrationShellDescriptor[AssetAdministrationShellDescriptor] |1..*
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|===

==== Operation DeleteAssetAdministrationShellDescriptorById

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[DeleteAssetAdministrationShellDescriptorById]]DeleteAssetAdministrationShellDescriptorById
h|Explanation 4+a|Deletes an Asset Administration Shell Descriptor, i.e., de-registers an AAS
h|semanticId 4+|`\https://admin-shell.io/aas/API/DeleteAssetAdministrationShellDescriptorById/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|aasIdentifier |The Asset Administration Shell’s unique id |yes |Identifier |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|===

==== Operation DeleteBulkAssetAdministrationShellDescriptorsById

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[DeleteBulkAssetAdministrationShellDescriptorsById]]DeleteBulkAssetAdministrationShellDescriptorsById
h|Explanation 4+a|Deletes multiple Asset Administration Shell Descriptors, i.e., de-registers multiple Asset Administration Shells
h|semanticId 4+|`\https://admin-shell.io/aas/API/DeleteBulkAssetAdministrationShellDescriptorsById/3/1`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|shellDescriptors |List of Asset Administration Shell Descriptor objects |yes | xref:specification/interfaces-payload.adoc#AssetAdministrationShellDescriptor[AssetAdministrationShellDescriptor] |1..*
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|===


==== Operation QueryAssetAdministrationShellDescriptors

[.table-with-appendix-table]
[width=100%, cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|QueryAssetAdministrationShellDescriptors
h|Explanation 4+a| Returns all Asset Administration Shell Descriptors that conform to a certain input query.
h|semanticId 4+|`\https://admin-shell.io/aas/API/QueryAssetAdministrationShellDescriptors/3/1`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|query | Query conforming to the AAS Query Language |yes | AAS Query |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |List of Asset Administration Shell Descriptors or AAS identifiers |no | xref:specification/interfaces-payload.adoc#QueryResult[QueryResult<AssetAdministrationShellDescriptor>]  |1..*
|===


=== Submodel Registry Interface and Operations

==== Submodel Registry Interface

[%autowidth,width="100%",cols="31%,69%",options="header",]
|===
2+|Interface: Submodel Registry
h|Operation Name h|Description
e|GetAllSubmodelDescriptors a|Returns all submodel descriptors
e|GetSubmodelDescriptorById a|Returns a specific submodel descriptor
e|PostSubmodelDescriptor a|Creates a new submodel descriptor, i.e., registers a submodel
e|PostBulkSubmodelDescriptors a|Creates one or more new submodel descriptors, i.e., registers several submodels
e|PutSubmodelDescriptorById a|Replaces an existing submodel descriptor, i.e., replaces registration information
e|PutBulkSubmodelDescriptorsById a|Replaces one or more existing submodel descriptors, i.e., replaces registration information of several submodels
e|DeleteSubmodelDescriptorById a|Deletes a submodel descriptor, i.e., de-registers a submodel
e|DeleteBulkSubmodelDescriptorsById a|Deletes one or more submodel descriptors, i.e., de-registers several submodels
| QuerySubmodelDescriptors a| Returns all Submodel Descriptors that conform to a certain input query.
|===

==== Operation GetAllSubmodelDescriptors

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[GetAllSubmodelDescriptors]]GetAllSubmodelDescriptors
h|Explanation 4+a|Returns all submodel descriptors
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetAllSubmodelDescriptors/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
e|limit a|The maximum size of the result set |no |nonNegativeInteger |1
e|cursor a|The position from which to resume a result listing |no |string |1
5+h|Output Parameter
e|statusCode a| StatusCode |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
e|payload a|List of requested submodel descriptors |no |SubmodelDescriptor |1..*
|===

==== Operation GetSubmodelDescriptorById

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[GetSubmodelDescriptorById]]GetSubmodelDescriptorById
h|Explanation 4+a|Returns a specific Submodel Descriptor
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetSubmodelDescriptorById/3/0`
=
h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
e|submodelIdentifier a|The Submodel’s unique id |yes |Identifier |1
5+h|Output Parameter
e|statusCode a|Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
e|payload a|Requested submodel descriptor |yes |SubmodelDescriptor |1
|===

==== Operation PostSubmodelDescriptor

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[PostSubmodelDescriptor]]PostSubmodelDescriptor
h|Explanation 4+a|Creates a new submodel descriptor, i.e. registers a submodel
h|semanticId 4+|`\https://admin-shell.io/aas/API/PostSubmodelDescriptor/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
e|submodel +
Descriptor a|Object containing the Submodel’s identification and endpoint information |yes |xref:specification/interfaces-payload.adoc#SubmodelDescriptor[SubmodelDescriptor] |1
5+h|Output Parameter
e|statusCode a|Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
e|payload a|Created submodel descriptor |yes | xref:specification/interfaces-payload.adoc#SubmodelDescriptor[SubmodelDescriptor]  |1
|===

==== Operation PostBulkSubmodelDescriptors

[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|PostBulkSubmodelDescriptors
h|Explanation    4+a|Creates one or more new submodel descriptors, i.e., registers several submodels
h|semanticId 4+|`\https://admin-shell.io/aas/API/PostBulkSubmodelDescriptors/3/1

h|Name h|Description h|Mand. h|Type h|Card.

5+h|Input Parameter

|submodel +
Descriptor    a|Object containing the Submodel’s identification and endpoint information |yes    | xref:specification/interfaces-payload.adoc#SubmodelDescriptor[SubmodelDescriptor]    |1..*

5+h|Output Parameter

|statusCode    a|Status code    |yes    |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode]    |1
|===

==== Operation PutSubmodelDescriptorById

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[PutSubmodelDescriptorById]]PutSubmodelDescriptorById
h|Explanation 4+a|Replaces an existing submodel descriptor, i.e., replaces registration information
h|semanticId 4+|`\https://admin-shell.io/aas/API/PutSubmodelDescriptorById/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
e|submodel +
Descriptor a|Object containing the Submodel’s identification and endpoint information |yes | xref:specification/interfaces-payload.adoc#SubmodelDescriptor[SubmodelDescriptor]  |1
5+h|Output Parameter
e|xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] a|Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
e|payload a|Replaced submodel descriptor |no | xref:specification/interfaces-payload.adoc#SubmodelDescriptor[SubmodelDescriptor]  |1
|===

==== Operation PutBulkSubmodelDescriptorsById

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|PutBulkSubmodelDescriptorsById
h|Explanation 4+a|Replaces one or more existing submodel descriptors, i.e., replaces registration information of several submodels
h|semanticId 4+|`\https://admin-shell.io/aas/API/PutBulkSubmodelDescriptorsById/3/1

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|submodel +
Descriptor |Object containing the Submodel’s identification and endpoint information |yes | xref:specification/interfaces-payload.adoc#SubmodelDescriptor[SubmodelDescriptor]  |1..*
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Replaced submodel descriptor |yes | xref:specification/interfaces-payload.adoc#SubmodelDescriptor[SubmodelDescriptor]  |1
|===

==== Operation DeleteSubmodelDescriptorById

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[DeleteSubmodelDescriptorById]]DeleteSubmodelDescriptorById
h|Explanation 4+a|Deletes a Submodel Descriptor, i.e., de-registers a submodel
h|semanticId 4+|`\https://admin-shell.io/aas/API/DeleteSubmodelDescriptorById/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|submodelIdentifier |The Submodel’s unique id |yes |Identifier |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|===

==== Operation DeleteBulkSubmodelDescriptorsById

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|DeleteBulkSubmodelDescriptorsById
h|Explanation 4+a|Deletes one or more submodel descriptors, i.e., de-registers several submodels
h|semanticId 4+|`\https://admin-shell.io/aas/API/DeleteBulkSubmodelDescriptorsById/3/1

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|submodelIdentifier |The Submodel’s unique id |yes |Identifier |1..*
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|===

==== Operation QuerySubmodelDescriptors

[.table-with-appendix-table]
[width=100%, cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|QuerySubmodelDescriptors
h|Explanation 4+a| Returns all Submodel Descriptors that conform to a certain input query.
h|semanticId 4+|`\https://admin-shell.io/aas/API/QuerySubmodelDescriptors/3/1`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|query | Query conforming to the AAS Query Language |yes | AAS Query |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |List of Submodel Descriptors or Submodel identifiers |no | xref:specification/interfaces-payload.adoc#QueryResult[QueryResult<SubmodelDescriptor>]  |1..*
|===


== Repository Interfaces

=== General

These interfaces allow to manage Asset Administration Shells, Submodels, and Concept Descriptions.
They further provide access to the data of these elements through interfaces described in <<aas-interfaces>>.
A repository can host multiple entities.
These entities can be stored in individual repositories of a decentral system.
The endpoints of the entities managed by one repository shall be resolved by subsequent calls to discover (<<publish-and-discovery-interfaces>>) and lookup (<<registration-interfaces>>) interfaces to such decentralized systems.

Sometimes, these kinds of services are also classified as Asset Administration Shell management services.

The interfaces that provide access to the entities (Asset Administration Shells, Submodels, Concept Descriptions) themselves are convenience interfaces that provide access in a system where the services are managed by central repositories.

=== Asset Administration Shell Repository Interface and Operations

==== Asset Administration Shell Repository Interface

[%autowidth,width="100%",cols="41%,59%",options="header",]
|===
2+|Interface: Asset Administration Shell Repository
h|Operation Name h|Description
e|GetAllAssetAdministrationShells |Returns all Asset Administration Shells
e|GetAssetAdministrationShellById |Returns a specific Asset Administration Shell
e|GetAllAssetAdministrationShellsByAssetId |Returns all Asset Administration Shells that are linked to a globally unique asset identifier or to specific asset ids
e|GetAllAssetAdministrationShellsByIdShort |Returns all Asset Administration Shells with a specific idShort
e|PostAssetAdministrationShell a|
Creates a new Asset Administration Shell.
The id of the new Asset Administration Shell must be set in the payload.

====
Note: the creation of the idShort is out of scope and must be handled in a proprietary way.
====

e|PutAssetAdministrationShellById a|Replaces an existing Asset Administration Shell
e|DeleteAssetAdministrationShellById a|Deletes an Asset Administration Shell
e|QueryAssetAdministrationShells a| Returns all Asset Administration Shells that conform to a certain input query.
|===

==== Operation GetAllAssetAdministrationShells

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|GetAllAssetAdministrationShells
h|Explanation 4+a|Returns all Asset Administration Shells
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetAllAssetAdministrationShells/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
e|serializationModifier a|Defines the format of the response |yes |xref:specification/interfaces-operation-parameters.adoc#SerializationModifier[SerializationModifier]  |1
e|limit a|The maximum size of the result set |no |nonNegativeInteger |1
e|cursor a|The position from which to resume a result listing |no |string |1
5+h|Output Parameter
e|statusCode a|Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
e|payload a|List of Asset Administration Shells |no |AssetAdministrationShell |1..*
|===

==== Operation GetAssetAdministrationShellById

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|GetAssetAdministrationShellById
h|Explanation 4+a|Returns a specific Asset Administration Shell
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetAssetAdministrationShellById/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|id |The Asset Administration Shell’s unique id |yes |Identifier |1
|serializationModifier |Defines the format of the response |yes |xref:specification/interfaces-operation-parameters.adoc#SerializationModifier[SerializationModifier]  |1
|limit |The maximum size of the result set |no |nonNegativeInteger |1
|cursor |The position from which to resume a result listing |no |string |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Requested Asset Administration Shell |yes |AssetAdministrationShell |1
|===

==== Operation GetAllAssetAdministrationShellsByAssetId

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|GetAllAssetAdministrationShellsByAssetId
h|Explanation 4+a|Returns all Asset Administration Shells that are linked to a globally unique asset identifier or to specific asset ids
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetAllAssetAdministrationShellsByAssetId/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|key |The key of the AssetId The name of the specific asset identifier or the predefined name “_globalAssetId_” that would refer to the _AssetInformation/globalAssetId_ |yes |string |1
|keyIdentifier |The key identifier object |yes |string |1
|serializationModifier |Defines the format of the response |yes |xref:specification/interfaces-operation-parameters.adoc#SerializationModifier[SerializationModifier]  |1
|limit |The maximum size of the result set |no |nonNegativeInteger |1
|cursor |The position from which to resume a result listing |no |string |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Requested Asset Administration Shells |no |AssetAdministrationShell |1..*
|===

==== Operation GetAllAssetAdministrationShellsByIdShort

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|GetAllAssetAdministrationShellsByIdShort
h|Explanation 4+a|Returns all Asset Administration Shells with a specific _idShort_
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetAllAssetAdministrationShellsByIdShort/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|idShort |The Asset Administration Shell’s idShort |yes |NameType | 1
|serializationModifier |Defines the format of the response |yes |xref:specification/interfaces-operation-parameters.adoc#SerializationModifier[SerializationModifier]  | 1
|limit |The maximum size of the result set |no |nonNegativeInteger |1
|cursor |The position from which to resume a result listing |no |string |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Requested Asset Administration Shells |no |AssetAdministrationShell |1..*
|===

==== Operation PostAssetAdministrationShell

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|PostAssetAdministrationShell
h|Explanation 4+a|
Creates a new Asset Administration Shell.
The id of the new Asset Administration Shell must be set in the payload.


====
Note: the creation of the idShort is out of scope and must be handled in a proprietary way.
====


h|semanticId 4+|`\https://admin-shell.io/aas/API/PostAssetAdministrationShell/3/0`

h|Name h|Description h|Mand. h|Type h|Card.


5+h|Input Parameter
|aas |Asset Administration Shell object |yes |AssetAdministrationShell |1

5+h|Output Parameter

|statusCode a|Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1

|payload a|Created Asset Administration Shell |yes |AssetAdministrationShell |1
|===

==== Operation PutAssetAdministrationShellById

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|PutAssetAdministrationShellById
h|Explanation 4+a|Replaces an existing Asset Administration Shell
h|semanticId 4+|`\https://admin-shell.io/aas/API/PutAssetAdministrationShellById/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|aas |Asset Administration Shell object |yes |AssetAdministrationShell |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Replaced Asset Administration Shell |no |AssetAdministrationShell |1
|===

==== Operation DeleteAssetAdministrationShellById

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|DeleteAssetAdministrationShellById
h|Explanation 4+a|Deletes an Asset Administration Shell
h|semanticId 4+|`\https://admin-shell.io/aas/API/DeleteAssetAdministrationShellById/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|id |The Asset Administration Shell’s unique id |yes |Identifier |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|===


==== Operation QueryAssetAdministrationShells

[.table-with-appendix-table]
[width=100%, cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|QueryAssetAdministrationShells
h|Explanation 4+a| Returns all Asset Administration Shells that conform to a certain input query.
h|semanticId 4+|`\https://admin-shell.io/aas/API/QueryAssetAdministrationShells/3/1`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|query | Query conforming to the AAS Query Language |yes | AAS Query |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |List of Asset Administration Shells or AAS identifiers |no | xref:specification/interfaces-payload.adoc#QueryResult[QueryResult<AssetAdministrationShell>]  |1..*
|===


=== Submodel Repository Interface and Operations

==== Submodel Repository Interface

[%autowidth,width="100%",cols="44%,56%",options="header",]
|===
2+|Interface: Submodel Repository
h|Operation Name h|Description
e|GetAllSubmodels |Returns all Submodels
e|GetSubmodelById |Returns a specific Submodel
e|GetAllSubmodelsBySemanticId |Returns all Submodels with a specific SemanticId
e|GetAllSubmodelsBySupplementalSemanticId |Returns all Submodels with a specific SupplementalSemanticId
e|GetAllSubmodelsByIdShort |Returns all Submodels with a specific _idShort_
e|PostSubmodel a|
Creates a new Submodel.
The id of the new submodel must be set in the payload.


====
Note: the creation of the idShort is out of scope and must be handled in a proprietary way.
====


|PutSubmodelById a|Replaces an existing Submodel
|PatchSubmodelById a|Updates an existing submodel
|DeleteSubmodelById a|Deletes a Submodel
e|QuerySubmodels a| Returns all Submodels that conform to a certain input query.
|===

==== Operation GetAllSubmodels

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|GetAllSubmodels
h|Explanation 4+a|Returns all Submodels
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetAllSubmodels/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|serializationModifier |Defines the format of the response |yes |xref:specification/interfaces-operation-parameters.adoc#SerializationModifier[SerializationModifier] |1
|limit |The maximum size of the result set |no |nonNegativeInteger |1
|cursor |The position from which to resume a result listing |no |string |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |List of Submodels |no |Submodel |1..*
|===

==== Operation GetSubmodelById

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|GetSubmodelById
h|Explanation 4+a|Returns a specific Submodel
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetSubmodelById/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|id |The Submodel’s unique id |yes |Identifier |1
|serializationModifier |Defines the format of the response |yes |xref:specification/interfaces-operation-parameters.adoc#SerializationModifier[SerializationModifier]  |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Requested Submodel |yes |Submodel |1
|===

==== Operation GetAllSubmodelsBySemanticId

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|GetAllSubmodelsBySemanticId
h|Explanation 4+a|
Returns all Submodels with a specific SemanticId or SupplementalSemanticId.
If either the semanticId fits to the input parameter or at least one of the SupplementalSemanticIds, the submodel is returned.
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetAllSubmodelsBySemanticId/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|semanticId |Identifier of the semantic definition |yes |Reference |1
|serializationModifier |Defines the format of the response |yes |xref:specification/interfaces-operation-parameters.adoc#SerializationModifier[SerializationModifier]  |1
|limit |The maximum size of the result set |no |nonNegativeInteger |1
|cursor |The position from which to resume a result listing |no |string |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Requested Submodels |no |Submodel |1..*
|===

==== Operation GetAllSubmodelsByIdShort

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|GetAllSubmodelsByIdShort
h|Explanation 4+a|Returns all Submodels with a specific _idShort_
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetAllSubmodelsByIdShort/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|idShort |The Submodel’s idShort |yes |NameType |1
|serializationModifier |Defines the format of the response |yes |xref:specification/interfaces-operation-parameters.adoc#SerializationModifier[SerializationModifier]  |1
|limit |The maximum size of the result set |no |nonNegativeInteger |1
|cursor |The position from which to resume a result listing |no |string |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Requested Submodels |no |Submodel |1..*
|===

==== Operation PostSubmodel

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|PostSubmodel
h|Explanation 4+a|
Creates a new Submodel.
The id of the new submodel must be set in the payload.


====
Note: the creation of the idShort is out of scope and must be handled in a proprietary way.
====


h|semanticId 4+|`\https://admin-shell.io/aas/API/PostSubmodel/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|submodel |Submodel object |yes |Submodel |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Created Submodel |yes |Submodel |1
|===

==== Operation PutSubmodelById

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|PutSubmodelById
h|Explanation 4+a|Replaces an existing Submodel
h|semanticId 4+|`\https://admin-shell.io/aas/API/PutSubmodelById/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|submodel |Submodel object |yes |Submodel |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Replaced Submodel | no |Submodel |1
|===

==== Operation PatchSubmodelById

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|PatchSubmodelById
h|Explanation 4+a|Updates an existing Submodel
h|semanticId 4+|`\https://admin-shell.io/aas/API/PatchSubmodelById/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|SerializationModifier  a|
Defines the format of the input


====
Note: values remain unchanged with content=metadata.
====


|yes |xref:specification/interfaces-operation-parameters.adoc#SerializationModifier[SerializationModifier] |1
|submodel |Submodel object |yes |Submodel |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Updated submodel |no |Submodel |1
|===

==== Operation DeleteSubmodelById

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|DeleteSubmodelById
h|Explanation 4+a|Deletes a Submodel
h|semanticId 4+|`\https://admin-shell.io/aas/API/DeleteSubmodelById/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
e|id a|The Submodel’s unique id |yes |Identifier |1
5+h|Output Parameter
e|statusCode a|Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|===



==== Operation QuerySubmodels

[.table-with-appendix-table]
[width=100%, cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|QuerySubmodels
h|Explanation 4+a| Returns all Submodels that conform to a certain input query.
h|semanticId 4+|`\https://admin-shell.io/aas/API/QuerySubmodels/3/1`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|query | Query conforming to the AAS Query Language |yes | AAS Query |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |List of Submodels or Submodel identifiers |no | xref:specification/interfaces-payload.adoc#Submodel[Submodel]  |1..*
|===


=== Concept Description Repository Interface and Operations

==== Concept Description Repository Interface

[%autowidth,width="100%",cols="55%,45%",options="header",]
|===
2+|Interface: Concept Description Repository
h|Operation Name h|Description
e|GetAllConceptDescriptions |Returns all Concept Descriptions
e|GetConceptDescriptionById |Returns a specific Concept Description
e|GetAllConceptDescriptionsByIdShort |Returns all Concept Descriptions with a specific _idShort_
e|GetAllConceptDescriptionsByIsCaseOf |Returns all Concept Descriptions with a specific _IsCaseOf_-reference
e|GetAllConceptDescriptionsByDataSpecificationReference |Returns all Concept Descriptions with a specific _dataSpecification_ reference
e|PostConceptDescription a|
Creates a new Concept Description.
The id of the new Concept Description must be set in the payload.


====
Note: the creation of the idShort is out of scope and must be handled in a proprietary way.
====


e|PutConceptDescriptionById |Replaces an existing Concept Description
e|DeleteConceptDescriptionById |Deletes a Concept Description
e|QueryConceptDescriptions | Returns all Concept Descriptions that conform to a certain input query.
|===

==== Operation GetAllConceptDescriptions

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|GetAllConceptDescriptions
h|Explanation 4+a|Returns all Concept Descriptions
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetAllConceptDescriptions/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|limit |The maximum size of the result set |no |nonNegativeInteger |1
|cursor |The position from which to resume a result listing |no |String |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |List of Concept Descriptions |no |ConceptDescription |1..*
|===

==== Operation GetConceptDescriptionById

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|GetConceptDescriptionById
h|Explanation 4+a|Returns a specific Concept Description
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetConceptDescriptionById/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|id |The Concept Description’s unique id |yes |Identifier |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Requested Concept Description |yes |ConceptDescription |1
|===

==== Operation GetAllConceptDescriptionsByIdShort

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|GetAllConceptDescriptionsByIdShort
h|Explanation 4+a|Returns all Concept Descriptions with a specific _idShort_
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetAllConceptDescriptionsByIdShort/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|idShort |The Concept Description’s idShort |yes |NameType |1
|limit |The maximum size of the result set |no |nonNegativeInteger |1
|cursor |The position from which to resume a result listing |no |string |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Requested Concept Descriptions |no |ConceptDescription |1..*
|===

==== Operation GetAllConceptDescriptionsByIsCaseOf

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|GetAllConceptDescriptionsByIsCaseOf
h|Explanation 4+a|Returns all Concept Descriptions with a specific _IsCaseOf_ reference
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetAllConceptDescriptionsByIsCaseOf/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|isCaseOf |IsCaseOf reference |yes |Reference |1
|limit |The maximum size of the result set |no |nonNegativeInteger |1
|cursor |The position from which to resume a result listing |no |string |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode]  |1
|payload |Requested Concept Descriptions |no |ConceptDescription |1..*
|===

==== Operation GetAllConceptDescriptionsByDataSpecificationReference

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|GetAllConceptDescriptionsByDataSpecificationReference
h|Explanation 4+a|Returns all Concept Descriptions with a specific _dataSpecification_ reference
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetAllConceptDescriptionsByDataSpecificationReference/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|dataSpecification-Reference |_DataSpecification_ reference |yes |Reference |_1_
|limit |The maximum size of the result set |no |nonNegativeInteger |1
|cursor |The position from which to resume a result listing |no |string |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Requested Concept Descriptions |no |ConceptDescription |1..*
|===

==== Operation PostConceptDescription

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|PostConceptDescription
h|Explanation 4+a|
Creates a new Concept Description.
The id of the new Concept Description must be set in the payload.


====
Note: the creation of the idShort is out of scope and must be handled in a proprietary way.
====


h|semanticId 4+|`\https://admin-shell.io/aas/API/PostConceptDescription/3/0`

h|Name h|Description h|Mand. h|Type h|Card.

5+h|Input Parameter

|conceptDescription a|Concept Description object |yes |ConceptDescription |1

5+h|Output Parameter

|statusCode a|Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode]  |1
|payload a|Created Concept Description |yes |ConceptDescription |1
|===

==== Operation PutConceptDescriptionById

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|PutConceptDescriptionById
h|Explanation 4+a|Replaces an existing Concept Description
h|semanticId 4+|`\https://admin-shell.io/aas/API/PutConceptDescriptionById/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|conceptDescription |Concept Description object |yes |ConceptDescription |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Replaced Concept Description |no |ConceptDescription |1
|===

==== Operation DeleteConceptDescriptionById

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|DeleteConceptDescriptionById
h|Explanation 4+a|Deletes a Concept Description
h|semanticId 4+|`\https://admin-shell.io/aas/API/DeleteConceptDescriptionById/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|cdIdentifier |The Concept Description’s unique id |yes |Identifier |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|===

==== Operation QueryConceptDescriptions

[.table-with-appendix-table]
[width=100%, cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|QueryConceptDescriptions
h|Explanation 4+a|Returns a list of Concept Descriptions based on an input query.
h|semanticId 4+|`\https://admin-shell.io/aas/API/QueryConceptDescriptions/3/1`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|query | The specific query conformant to the AAS Query Language, containing filter conditions for the required Concept Descriptions. | yes | Query |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload | List of requested Concept Descriptions or identifiers |no | xref:specification/interfaces-payload.adoc#QueryResult[QueryResult<ConceptDescription>] |1..*
|===



[#publish-and-discovery-interfaces]
== Publish and Discovery Interfaces

=== General

These interfaces allow to publish information about Asset Administration Shells that enable a search for asset IDs of the corresponding Asset Administration Shells in a subsequent discovery interface call.

=== Asset Administration Shell Basic Discovery Interface and Operations

==== Asset Administration Shell Basic Discovery Interface

[%autowidth,width="100%",cols="45%,55%",options="header",]
|===
2+|Interface: Asset Administration Shell Basic Discovery
h|Operation Name h|Description
e|GetAllAssetAdministrationShellIdsByAssetLink |Returns a list of Asset Administration Shell ids based on asset identifier key-value-pairs
e|GetAllAssetLinksById |Returns a list of asset identifier key-value-pairs based on a given Asset Administration Shell id
e|PostAllAssetLinksById |Creates or replaces all asset identifier key-value-pairs linked to an Asset Administration Shell to edit discoverable content
e|DeleteAllAssetLinksById |Deletes all asset identifier key-value-pair linked to an Asset Administration Shell
|===

==== Operation GetAllAssetAdministrationShellIdsByAssetLink

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|GetAllAssetAdministrationShellIdsByAssetLink
h|Explanation 4+a|Returns a list of Asset Administration Shell ids based on asset identifier key-value-pairs
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetAllAssetAdministrationShellIdsByAssetLink/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|assetIds a|
The specific assetId of an asset identifier, which could be the globalAssetId or specificAssetIds.


====
Note: The key of the asset identifier key-value-pair for the globalAssetId is defined in Clause 4.5.
It is the predefined key “_globalAssetId_” that would refer to the _AssetInformation/globalAssetId_.
====


|no |SpecificAssetId |1..*
|limit |The maximum size of the result set |no |nonNegativeInteger |1
|cursor |The position from which to resume a result listing |no |string |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Identifiers of all Asset Administration Shells which contain all asset identifier key-value-pairs in their asset information, i.e. AND-match of key-value-pairs per Asset Administration Shell |no |Identifier |1..*
|===

==== Operation GetAllAssetLinksById

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|GetAllAssetLinksById
h|Explanation 4+a|Returns a list of asset identifier key-value-pairs based on an Asset Administration Shell id to edit discoverable content
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetAllAssetLinksById/3/0`


h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|aasIdentifier |The Asset Administration Shell’s unique id |yes |string |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload a|
Requested asset identifier, which could be the globalAssetId or specificAssetIds.


====
Note: the name of the SpecificAssetId for the globalAssetId is defined in Clause 4.5.
It is the predefined name “_globalAssetId_” that would refer to the _AssetInformation/globalAssetId_.
====


|no |SpecificAssetId |1..*
|===

==== Operation PostAllAssetLinksById

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|PostAllAssetLinksById
h|Explanation 4+a|
Creates new asset identifier key-value-pairs linked to an Asset Administration Shell for discoverable content.
The existing content might have to be deleted first.
h|semanticId 4+|`\https://admin-shell.io/aas/API/PostAllAssetLinksById/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|aasIdentifier |The Asset Administration Shell’s unique id |yes |string |1
|assetLinks a|
Asset identifier, which could be the globalAssetId or specificAssetIds.


====
Note: the name for the globalAssetId is defined in Clause 4.5.
It is the predefined key “_globalAssetId_” that would refer to the _AssetInformation/globalAssetId_.
====


|yes |SpecificAssetId |1..*
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|payload |Asset identifier created successfully |yes |SpecificAssetId |1
|===

==== Operation DeleteAllAssetLinksById

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|DeleteAllAssetLinksById
h|Explanation 4+a|Deletes all asset identifier key-value-pairs linked to an Asset Administration Shell to edit discoverable content
h|semanticId 4+|`\https://admin-shell.io/aas/API/DeleteAllAssetLinksById/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
|aasIdentifier |The Asset Administration Shell’s unique id |yes |string |1
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|===

== Self Description Interface

=== Self-Description Interface

[%autowidth,width="100%",cols="19%,81%",options="header",]
|===
2+|Interface: Self-Description
h|Operation Name h|Description
e|GetSelfDescription |Returns a description object containing the capabilities and supported features of the server.
|===

=== Operation GetSelfDescription

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[GetSelfDescription]]GetSelfDescription
h|Explanation 4+a|Returns a description object containing the capabilities and supported features of the server.
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetSelfDescription/3/0`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Output Parameter
|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
|description |Key-value-pairs that describe the capabilities of the providing server |yes |ServiceDescription |1
|===

====
Note 1: a server implementing more than one service specification profile, e.g. hosting a repository and a registry at the same time, adds both ServiceSpecificationProfileEnum items in the profiles list.
====

====
Note 2: a profile value must only be used if the related API is implemented at the path where the API Operation “GetDescription” is published, or child paths.
====


