openapi: 3.0.3
info:
  title: DotAAS Part 2 | HTTP/REST | Concept Description Repository Service Specification
  description: >-
    The Signature Profile of the ConceptDescription Repository Service Specification as part of [Specification of the Asset Administration Shell: Part 2](https://industrialdigitaltwin.org/en/content-hub/aasspecifications).  
  
    Copyright: Industrial Digital Twin Association (IDTA) March 2026
  contact:
    name: Industrial Digital Twin Association (IDTA)
    email: info@idtwin.org
  license: 
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  version: V3.2.0_SSP-003
  x-profile-identifier: https://admin-shell.io/aas/API/3/2/ConceptDescriptionRepositoryServiceSpecification/SSP-003
  termsOfService: https://github.com/admin-shell-io/aas-specs-metamodel
servers:
- url: 'https://admin-shell.io/api/v3/'
- url: 'https://example.com/'
paths:
  /concept-descriptions/{cdIdentifier}/$signed:
    get:
      tags:
        - Concept Description Repository API
      summary: Returns a specific Concept Description as a JWS string.
      operationId: GetConceptDescriptionByIdSigned
      x-semanticIds:
        - https://admin-shell.io/aas/API/GetConceptDescriptionByIdSigned/3/2
      parameters:
        - name: cdIdentifier
          in: path
          description: The Concept Description’s unique id (UTF8-BASE64-URL-encoded)
          required: true
          style: simple
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: Requested Concept Description as a JWS string.
          content:
            text/plain:
              schema:
                type: string
                format: jwt
                description: A JWS string containing the requested Concept Description.
        '400':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/bad-request'
        '403':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/forbidden'
        '404':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/not-found'
        '500':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/internal-server-error'
        default:
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/default'

  /description:
    get:
      tags:
        - Description API
      summary: Returns the self-describing information of a network resource (ServiceDescription)
      operationId: GetSelfDescription
      x-semanticIds:
        - https://admin-shell.io/aas/API/GetSelfDescription/3/2
      responses:
        '200':
          description: Requested Description
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/schemas/ServiceDescription'
        '403':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/forbidden'
