@startuml
!theme idta from https://raw.githubusercontent.com/admin-shell-io/aas-specs-antora/main/plantuml/

allow_mixing

object Submodel {
    Id = "https://admin-shell.io/sampleSM"
}
object SubmodelElementStruct {
    IdShort = "sme1"
}
object SubmodelElementList {
    IdShort = "sme2"
}
object "          Entity           " as Entity {
    Index = 0
}
object "       Property      " as Property {
    IdShort = "p1"
}

Submodel --> "submodelElement" SubmodelElementStruct
SubmodelElementStruct --> "value" SubmodelElementList
SubmodelElementList --> "value" Entity
Entity --> "statement" Property

note right of SubmodelElementStruct: idShort-path:\n"sme1"
note right of SubmodelElementList: idShort-path:\n"sme1.sme2"
note right of Entity: idShort-path:\n"sme1.sme2[0]"
note right of Property: idShort-path:\n"sme1.sme2[0].p1"

@enduml
