@startuml
!theme idta from https://raw.githubusercontent.com/admin-shell-io/aas-specs-antora/main/plantuml/
participant Client as "Client Application"

box "Discovery Service"
  participant AASDiscovery as "AAS Discovery Interface"
end box

box "AAS Registry Service"
   participant AASRegistry as "AAS Registy Interface"
end box

box "Submodel Registry Service"
   participant SMRegistry as "Submodel Registy Interface"
end box

box "AAS or AAS Repository Service"
  participant iAAS as "AAS or AAS Repository Interface"
end box

box "Submodel or Submodel Repository Service"
  participant iSM as "Submodel or Submodel Repository Interface"
end box

activate Client
Client -> Client : selection asset links

Client -> AASDiscovery: SearchAllAssetAdministrationShellIdsByAssetLink
activate AASDiscovery
Client <-- AASDiscovery : IDs of AAS
deactivate AASDiscovery
Client -> Client : select AAS ID


Client -> AASRegistry : GetAssetAdministrationShellDescriptorById
activate AASRegistry
Client <-- AASRegistry : AAS Descriptor with AAS Endpoint
deactivate AASRegistry

Client -> iAAS : GetAssetAdministrationShell or GetAssetAdministrationShellById
activate iAAS
note left
get AAS
via Endpoint
end note
Client <-- iAAS : AAS with Submodel IDs
deactivate iAAS
Client -> Client : extract relevant Submodel IDs

Client -> SMRegistry : GetSubmodelDescriptorById
activate SMRegistry
Client <-- SMRegistry: SubmodelDescritpor with endpoint of Submodel
deactivate SMRegistry


Client -> iSM : GetSubmodel or GetSubmodelById
activate iSM
note left
get submodel
via Endpoint
end note
Client <-- iSM : Submodel
deactivate iSM



@enduml
