@startuml

participant DPPClient as "DPP Client"

box "DPP Service"
participant Client as "DPP Application"
end box



box "AAS Registry Service"
   participant AASRegistry as "AAS Registry Interface"
end box

box "Submodel Registry Service"
   participant SubmodelRegistry as "Submodel Registry Interface"
end box

box "AAS Repository Service"
  participant AASService as "AAS Interface"
end box

box "Submodel Repository Service"
  participant SMService as "Submodel Interface"
end box

activate DPPClient
DPPClient -> Client : ReadDPPVersionByIdAndDate(dppId,date)

activate Client
Client <- Client : map dppId to aasId



Client -> AASRegistry : GetAssetAdministrationShellDescriptorByIdAndDate
activate AASRegistry
Client <-- AASRegistry : AAS Descriptor with AAS Endpoint
deactivate AASRegistry
Client -> AASService : GetAssetAdministrationShellVersionByIdAndDate  via Endpoint
activate AASService
Client <-- AASService : AAS
deactivate AASService

Client -> Client : extract  Submodel ID for DPP Metadata


Client -> SubmodelRegistry : GetSubmodelDescriptorByIdAndDate via Endpoint
activate SubmodelRegistry
Client <-- SubmodelRegistry : Submodel Descriptor for DPP Metadata
deactivate SubmodelRegistry

Client -> SMService : GetSubmodelVersionByIdAndDate
activate SMService
Client <-- SMService : DPP Metadata Submodel
deactivate SMService

Client -> Client : extract relevant Submodel Endpoints
note left of Client
  i.e. content Submodels with 
  semanticId   as specified 
  in contentSpecificationIds
end note
loop for all relevant Submodels
Client -> SMService : GetSubmodelVersionByIdAndDate via Endpoint
activate SMService
Client <-- SMService : content Submodel
deactivate SMService
end

Client <- Client : serialize and assemble DPP document
DPPClient <-- Client : return DPP
deactivate Client
deactivate DPPClient

@enduml