[bibliography]
== Bibliography

[#bib1]
[1] IDTA-01001-3-1. Specification of the Asset Administration Shell.
Part 1: Metamodel.
Industrial Digital Twin Association (IDTA).
Online.
Available: https://industrialdigitaltwin.org/en/content-hub/aasspecifications

[#bib2]
[2] IDTA-01003-a-3-1. Specification of the Asset Administration Shell.
Part 3a: Data Specification – IEC 61360. Industrial Digital Twin Association (IDTA).
Online.
Available: https://industrialdigitaltwin.org/en/content-hub/aasspecifications

[#bib3]
[3] IDTA-01004-3-1. Specification of the Asset Administration Shell. 
Part 4: Security. Industrial Digital Twin Association (IDTA). 
Online. 
Available: https://industrialdigitaltwin.org/en/content-hub/aasspecifications

[#bib4]
[4] IDTA-01005-3-1. Specification of the Asset Administration Shell.
Part 5: Package File Format.
Industrial Digital Twin Association (IDTA).
Online.
Available: https://industrialdigitaltwin.org/en/content-hub/aasspecifications

[#bib5]
[5] RFC 8820: URI Design and Ownership.
Internet Engineering Task Force (IETF), 2020. Online.
Available: https://tools.ietf.org/html/rfc8820

[#bib6]
[6] DIN EN IEC 61406-1: "Identification Link - Part 1: General requirements (IEC 61406-1:2022)".
December 2023. Online.
Available: https://www.dinmedia.de/en/standard/din-en-iec-61406-1/372053652

[#bib7]
[7] Decentralized Identifiers (DIDs) v1.0. Edited by Manu Sporny, Amy Guy, Markus Sabadello, and Drummond Reed.
W3C Recommendation.
Online.
Available: https://www.w3.org/TR/did-core/

[#bib8]
[8] OData Version 4.01 Part 1: Protocol.
Edited by Michael Pizzo, Ralf Handl, and Martin Zurmuehl.
OASIS Standard.
Online.
Available: https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html

[#bib9]
[9] Tom Preston-Werner.
Semantic Versioning.
Version 2.0.0. Online.
Available: https://semver.org/spec/v2.0.0.html

[#bib10]
[10] "OMG Unified Modelling Language (OMG UML)".
Formal/2017-12-05. 
Version 2.5.1. 
December 2018.
Online.
Available: https://www.omg.org/spec/UML/

[#bib11]
[11] "RQL: A resource query language for REST".
Ariel Mashraki
Version 1.3.0. 
March 2021.
Online.
Available: https://github.com/a8m/rql

[#bib12]
[12] "SPARQL 1.1 Query Language".
W3C Recommendation. 
Edited by Steve Harris and Andy Seaborne
March 2013.
Online.
Available: https://www.w3.org/TR/sparql11-query/

[#bib13]
[13] ISO/IEC 39075:2024. Information technology — Database languages — GQL.
ISO/IEC. 
2024.
Online.
Available: https://www.iso.org/standard/76120.html

[#bib14]
[14] "JSONPath - XPath for JSON".
Stefan Gössner
2007.
Online.
Available: http://goessner.net/articles/JsonPath/

