== Terms, Definitions and Abbreviations

=== Terms and Definitions

====
[.underline]#Please note#: the definitions of terms are only valid in a certain context. This glossary applies only within the context of this document.
====

If available, definitions were taken from IEC 63278-1 DRAFT, July 2022.

*API*

specification of the set of operations and events that forms an API in a selected technology

*API Operation*

specification of the operations (procedures) that may be called through an API

*Asset Administration Shell (AAS)*

standardized digital representation of an asset


====
Note: Asset Administration Shell and Administration Shell are used synonymously.
====


* [SOURCE: IEC 63278-1, note added]

*Interface*

defined connection point of a functional unit which can be connected to other functional units


====
Note 1: “defined” means that the requirements and the assured properties of this connection point are described.

Note 2: the combination of interfaces of function units is also called an interface.

Note 3: in an information system, the defined exchange of information takes place at this point.

Note 4: an interface places certain requirements on the connection that is to be made.

Note 5: an interface demands certain features.
====


[Source: Glossary Industrie 4.0

DUDEN (modified)

ISO/IEC 13066-1:2011(en), 2.15 (modified)

DIN EN 60870-5-6:2009-11 (modified)

DIN IEC 60625-1:1981-05 (modified)]

*Interface Operation*

interface operations define interaction patterns via the specified interface

*operation*

executable realization of a function


====
Note 1: the term method is synonymous to operation.

Note 2: an operation has a name and a list of parameters [ISO 19119:2005, 4.1.3].
====


* [SOURCE: Glossary Industrie 4.0, editorial changes]

*service*

Demarcated scope of functionality which is offered by an https://www.plattform-i40.de/PI40/Redaktion/EN/Glossary/E/entity_glossary.html[entity] or organization via https://www.plattform-i40.de/PI40/Redaktion/EN/Glossary/I/interface_glossary.html[interfaces]


====
Note: one or multiple operations can be assigned to one service.
====


* [SOURCE: Glossary Industrie 4.0]

*service specification*

specification of a service according to the notation, architectural style and constraints of a selected technology


====
Note: one or multiple API Operations can be assigned to one service specification.
====


*Submodel*

representation of an aspect of an asset

* [SOURCE: IEC 63278-1]

*SubmodelElement*

element of a Submodel

* [SOURCE: IEC 63278-1]

=== Abbreviations

[%autowidth, width="100%", cols="21%,79%",options="header",]
|===
|*Abbreviation* |*Description*
|AAS |Asset Administration Shell
|AASX |Package file format for the AAS
|AML |AutomationML
|API |Application Programming Interface
|BITKOM |Bundesverband Informationswirtschaft, Telekommunikation und neue Medien e. V.
|BLOB |Binary Large Object
|CDD |Common Data Dictionary
|GUID |Globally unique identifier
|ID |Identifier
|IDTA |Industrial Digital Twin Association
|IEC |International Electrotechnical Commission
|IRDI |International Registration Data Identifier
|ISO |International Organization for Standardization
|JSON |JavaScript Object Notation
|MIME |Multipurpose Internet Mail Extensions
|OPC |Open Packaging Conventions (ECMA-376, ISO/IEC 29500-2)
|OPCF |OPC Foundation
|OPC UA |OPC Unified Architecture
|PDF |Portable Document Format
|RAMI4.0 |Reference Architecture Model Industrie 4.0
|RDF |Resource Description Framework
|REST |Representational State Transfer
|RFC |Request for Comment
|ROA |Resource Oriented Architecture
|SOA |Service Oriented Architecture
|UML |Unified Modeling Language
|URI, URL, URN |Uniform Resource Identifier, Locator, Name
|VDE |Verband der Elektrotechnik Elektronik Informationstechnik e. V.
|VDI |Verein Deutscher Ingenieure e.V.
|VDMA |Verband Deutscher Maschinen- und Anlagenbau e.V.
|W3C |World Wide Web Consortium
|XML |eXtensible Markup Language
|ZIP |archive file format that supports lossless data compression
|ZVEI |Zentralverband Elektrotechnik- und Elektronikindustrie e. V.
|===