////
Copyright (c) 2023 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/). 

SPDX-License-Identifier: CC-BY-4.0

////

= Preamble

== Editorial Notes

This document (version 3.1) was produced from November 2021 to October 2023 by the joint sub working group "Asset Administration Shell" of the working group "Reference Architectures, Standards and Norms" of the Plattform Industrie 4.0 and the working group "Open Technology" of the Industrial Digital Twin Association (IDTA). It enhances the first release (version 3.0) published by the Industrial Digital Twin Association in April 2023. 

Earlier versions of this document were release candidates and used the version 1.0. It has been decided in the meantime that this first release will start with version 3.0, in line with the related release of the metamodel.

Version 1.0 RC02 of this document was developed from November 2020 to November 2021 by the joint working groups “Asset Administration Shell” and “Infrastructure of the Asset Administration Shell” of the Plattform Industrie 4.0 working group “Reference Architectures, Standards and Norms“.

Version 1.0 RC01 of this document was developed from December 2019 to November 2020 by the sub working groups “Asset Administration Shell” and “Infrastructure of the Asset Administration Shell” of the Plattform Industrie 4.0 working group “Reference Architectures, Standards and Norms“.

This document is Part 2 of the document series “Specification of the Asset Administration Shell”.

This specification is versioned using Semantic Versioning 2.0.0 and follows the semver specification link:#bib4[[4\]].

== Metamodel Versions

This document (version 3.1) uses the following parts of the “Specification of the Asset Administration Shell” series:

* Part 1: Metamodel in version 3.1 link:#bib1[[1\]]
* Part 3a: Data Specification – IEC 61360 in version 3.1 link:#bib2[[2\]]
* Part 5: Package File Format (AASX) in version 3.1 link:#bib3[[3\]]

== Scope of this Document

This document specifies the interfaces as well as the APIs in selected technologies for the Asset Administration Shells and its submodels.

== Structure of the Document

Clause 3 gives an introduction to the topic. General topics are discussed in Clause 4. The technology-neutral specification of the interfaces of the Asset Administration Shell can be found in Clauses 5 to 11.

Clause 12 defines the API specification for HTTP/REST. Annex B gives an example for the ValueOnly-serialization of the payload.

Clause 13 provides a summary and outlook.

The tables used to specify operations and interfaces are explained in the annex. Additionally, non-normative examples are given to illustrate in particular the different serialization alternatives.

