= Part 2: Application Programming Interfaces (IDTA-01002-3-1)

*Specification of the Asset Administration Shell*

====
This specification is part of the https://industrialdigitaltwin.org/en/content-hub/aasspecifications[Asset Administration Shell Specification series].
====

== Version

This is version 3.1 of the specification IDTA-01002.

Previous version: 3.0.3

[#metamodel-versions]
== Metamodel Versions

This document (version 3.1) uses the following parts of the “Specification of the Asset Administration Shell” series:

* IDTA-01001 Part 1: Metamodel in version 3.1 xref:bibliography.adoc#bib1[[1\]]
* IDTA-01003-a Part 3a: Data Specification – IEC 61360 in version 3.1 xref:bibliography.adoc#bib2[[2\]]
* IDTA-01004 Part 4: Security in version 3.1 xref:bibliography.adoc#bib3[[3\]]
* IDTA-01005 Part 5: Package File Format (AASX) in version 3.1 xref:bibliography.adoc#bib4[[4\]]

== Notice

Publisher: Industrial Digital Twin Association e.V. (IDTA)

IDTA Document Number: IDTA-01002-3-1

DOI: <add DOI>

This work is licensed under a
https://creativecommons.org/licenses/by/4.0/[Creative Commons Attribution 4.0 International License].

SPDX-License-Identifier: CC-BY-4.0

== How to Get in Contact

Contact: https://industrialdigitaltwin.org/en/contact[IDTA]

Sources: https://github.com/admin-shell-io/aas-specs-api[GitHub]

Feedback:

* https://github.com/admin-shell-io/aas-specs-api/issues/new/choose[New issues, bugs]

* https://github.com/admin-shell-io/questions-and-answers[Questions and Answers]

[[editorial-notes]]
== Editorial Notes

=== History

This document (version 3.1) was produced by the Work Stream "Specification of the Asset Administration Shell" of the Working Group "Open Technology" of the https://industrialdigitaltwin.org/[Industrial Digital Twin Association (IDTA)].
It is the first version published as html document and maintained completely open source.

Version 3.0, the first release of the API, was finalized from November 2021 to May 2023 by the joint sub working group "Asset Administration Shell" of the working group "Reference Architectures, Standards and Norms" of the Plattform Industrie 4.0 and the working group "Open Technology" of the Industrial Digital Twin Association (IDTA). 

Earlier versions of this document were release candidates and used the version 1.0.
It has been decided in the meantime that this first release will start with version 3.0, in line with the related release of the metamodel.

Version 1.0 RC02 of this document was developed from November 2020 to November 2021 by the joint working groups “Asset Administration Shell” and “Infrastructure of the Asset Administration Shell” of the Plattform Industrie 4.0 working group “Reference Architectures, Standards and Norms“.

Version 1.0 RC01 of this document was developed from December 2019 to November 2020 by the sub working groups “Asset Administration Shell” and “Infrastructure of the Asset Administration Shell” of the Plattform Industrie 4.0 working group “Reference Architectures, Standards and Norms“.

This document is Part 2 of the document series “Specification of the Asset Administration Shell”.


include::./shared/versioning.adoc[]

include::./shared/conformance.adoc[]
