////
Copyright (c) 2023 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/). 

SPDX-License-Identifier: CC-BY-4.0

////

= Preamble

== Scope of this Document

This document specifies the interfaces as well as the APIs in selected technologies for the Asset Administration Shells and its submodels.

== Structure of the Document

xref:introduction.adoc[] gives an introduction to the topic.

General topics are discussed in xref:general.adoc[].

The technology-neutral specification of the interfaces of the Asset Administration Shell can be found in Clauses:

** xref:specification/interfaces.adoc[API Interfaces]

** xref:specification/interfaces-payload.adoc[Data Types for Payload]

** xref:specification/interfaces-operation-parameters.adoc[Basic Operation Parameters]

Following Clauses define the API specification for HTTP/REST:

** xref:http-rest-api/http-rest-api.adoc[HTTP/REST API]

** xref:http-rest-api/service-specifications-and-profiles.adoc[Service Profiles]

** xref:http-rest-api/interactions.adoc[Interactions]

** xref:http-rest-api/security.adoc[Security]

** xref:http-rest-api/api-code-generation.adoc[API Code Generation]

xref:summary-and-outlook.adoc[] provides a summary and outlook.

The tables used to specify operations and interfaces are explained in the annex.
Additionally, non-normative examples are given to illustrate in particular the different serialization alternatives.

