////
Copyright (c) 2023 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/). 

SPDX-License-Identifier: CC-BY-4.0

////

= Preamble

== Scope of this Document

This document specifies the interfaces as well as the APIs in selected technologies for the Asset Administration Shells and its submodels.

== Structure of the Document

xref:introduction.adoc[] gives an introduction to the topic.

General topics are discussed in xref:general.adoc[].

The query language is sepcified in xref:query-language.adoc[].

The technology-neutral specification of the interfaces of the Asset Administration Shell can be found in Clauses:

** xref:specification/interfaces.adoc[API Interfaces]

** xref:specification/interfaces-payload.adoc[Data Types for Payload]

** xref:specification/interfaces-operation-parameters.adoc[Basic Operation Parameters]

Following Clauses define the API specification for HTTP/REST:

** xref:http-rest-api/http-rest-api.adoc[HTTP/REST API]

** xref:http-rest-api/service-specifications-and-profiles.adoc[Service Profiles]

** xref:http-rest-api/interactions.adoc[Interactions]

** xref:http-rest-api/security.adoc[Security]

** xref:http-rest-api/api-code-generation.adoc[API Code Generation]

xref:summary-and-outlook.adoc[] provides a summary and outlook.


Annex xref:annex/serialization-modifier-examples.adoc[] contains examples for the serialization modifiers.

Annex xref:annex/backus-naur-form.adoc[] defines the grammar language used in the specification.
Annex xref:annex/uml.adoc[] contains information about UML, 
while Annex xref:annex/uml-templates.adoc[] provides the tables used to specify UML classes etc. as used in this specification.
Annex xref:annex/api-tables-templates.adoc[] explains the templates used to specify operations and interfaces. 

xref:annex/handling-constraints.adoc[] explains the numbering of constraints used in the specification. 
xref:annex/overview-constraints.adoc[] gives an (non-normative) overview of all constraints used in the documents.

The xref:changelog.adoc[] describes metamodel changes compared to previous versions.

Finally, a xref:bibliography.adoc[] is given.

