openapi: 3.0.3
info:
  title: DotAAS Part 2 | HTTP/REST | Submodel Service Specification - Value Profile
  description: The Value Profile of the Submodel Service Specification as part of Details of the Asset Administration Shell Part 2
  contact:
    name: Constantin Ziesche, Andreas Orzelski, Florian Krebs, Bastian Rössl, Manuel Sauer, Jens Vialkowitsch, Michael Hoffmeister, Torben Miny, Sebastian Bader, Marko Ristin, Nico Braunisch
  version: V3.0-ValueProfile
  termsOfService: https://github.com/admin-shell-io/aas-specs
servers:
- url: '{protocol}://{host_name}:{port}/api/{version_prefix}'
  variables:
    protocol:
      description: 'Allows access through http and https (recommended)'
      enum:
        - 'http'
        - 'https'
      default: 'https'
    host_name:
      default: admin-shell.io
      description: 'Hostname of server hosting the api'
    port:
      enum:
        - '80'
        - '443'
      default: '443'
      description: '80 is default for http, 443 for https'
    version_prefix:
      enum:
        - 'v3.0'
      default: v3.0
paths:
  /submodel:
    get:
      tags:
        - Submodel API
      summary: Returns the Submodel
      operationId: GetSubmodel
      x-semanticIds:
        - https://admin-shell.io/aas/API/GetSubmodel/3/0
      parameters:
        - $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/parameters/Extent'
      responses:
        '200':
          description: Requested Submodel
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0RC02#/components/schemas/Submodel'
        '400':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/bad-request'
        '403':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/forbidden'
        '500':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/internal-server-error'
        default:
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/default'
  /submodel/$value:
    get:
      tags:
        - Submodel API
      summary: Returns the Submodel in the ValueOnly representation
      operationId: GetSubmodelValueOnly
      x-semanticIds:
        - https://admin-shell.io/aas/API/GetSubmodelById/3/0
      parameters:
        - $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/parameters/Extent'
      responses:
        '200':
          description: ValueOnly representation of the Submodel
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/schemas/SubmodelValue'
        '400':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/bad-request'
        '403':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/forbidden'
        '500':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/internal-server-error'
        default:
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/default'
  /submodel/submodel-elements/{idShortPath}/invoke:
    post:
      tags:
        - Submodel API
      summary: Synchronously or asynchronously invokes an Operation at a specified path
      operationId: InvokeOperation
      x-semanticIds:
        - https://admin-shell.io/aas/API/InvokeOperationSync/3/0
      parameters:
        - name: idShortPath
          in: path
          description: IdShort path to the submodel element (dot-separated), in this case an operation
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        description: Operation request object
        content:
          application/json:
            schema:
              $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/schemas/OperationRequest'
        required: true
      responses:
        '200':
          description: Operation result object
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/schemas/OperationResult'
        '400':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/bad-request'
        '403':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/forbidden'
        '404':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/not-found'
        '405':
          description: Method not allowed - Invoke only valid for Operation submodel element
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/schemas/Result'
        '500':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/internal-server-error'
        default:
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/default'
  /description:
    get:
      tags:
        - Description API
      summary: Returns the self-describing information of a network resource (ServiceDescription)
      operationId: GetDescription
      x-semanticIds:
        - https://admin-shell.io/aas/API/Descriptor/GetDescription/3/0
      responses:
        '200':
          description: Requested Description
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/schemas/ServiceDescription'
        '403':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/forbidden'