openapi: 3.0.3
info:
  title: DotAAS Part 2 | HTTP/REST | AASX File Server Service Specification
  description: The File Server Service Specification as part of Details of the Asset Administration Shell Part 2
  contact:
    name: Constantin Ziesche, Andreas Orzelski, Florian Krebs, Bastian Rössl, Manuel Sauer, Jens Vialkowitsch, Michael Hoffmeister, Torben Miny, Sebastian Bader, Marko Ristin, Nico Braunisch
  version: V3.0
  termsOfService: https://github.com/admin-shell-io/aas-specs
paths:
  /packages:
    get:
      tags:
        - AASX File Server API
      summary: Returns a list of available AASX packages at the server
      operationId: GetAllAASXPackageIds
      x-semanticIds:
        - https://admin-shell.io/aas/API/GetAllAASXPackageIds/3/0
      parameters:
        - name: aasId
          in: query
          description: The Asset Administration Shell’s unique id (UTF8-BASE64-URL-encoded)
          required: false
          style: form
          explode: true
          schema:
            type: string
            format: byte
        - $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/parameters/From'
        - $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/parameters/Size'
      responses:
        '200':
          description: Requested package list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/schemas/PackageDescription'
        '400':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/bad-request'
        '500':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/internal-server-error'    
        default:
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/default'
    post:
      tags:
        - AASX File Server API
      summary: Stores the AASX package at the server
      operationId: PostAASXPackage
      x-semanticIds:
        - https://admin-shell.io/aas/API/PostAASXPackage/3/0
      requestBody:
        description: AASX package
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                aasIds:
                  type: array
                  items:
                    type: string
                file:
                  type: string
                  format: binary
                fileName:
                  type: string
            encoding:
              file:
                contentType: application/asset-administration-shell-package
        required: true
      responses:
        '201':
          description: AASX package stored successfully
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/schemas/PackageDescription'
        '400':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/bad-request'
        '500':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/internal-server-error'    
        default:
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/default'
  /packages/{packageId}:
    get:
      tags:
        - AASX File Server API
      summary: Returns a specific AASX package from the server
      operationId: GetAASXByPackageId
      x-semanticIds:
        - https://admin-shell.io/aas/API/GetAASXByPackageId/3/0
      parameters:
        - name: packageId
          in: path
          description: The package Id (UTF8-BASE64-URL-encoded)
          required: true
          style: simple
          explode: true
          schema:
            type: string
            format: byte
      responses:
        '200':
          description: Requested AASX package
          headers:
            X-FileName:
              schema:
                type: string
              description: Filename of the package
          content:
            application/asset-administration-shell-package:
              schema:
                type: string
                format: binary
        '400':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/bad-request'
        '404':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/not-found'
        '500':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/internal-server-error'    
        default:
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/default'
    put:
      tags:
        - AASX File Server API
      summary: Updates the AASX package at the server
      operationId: PutAASXByPackageId
      x-semanticIds:
        - https://admin-shell.io/aas/API/PutAASXByPackageId/3/0
      parameters:
        - name: packageId
          in: path
          description: The Package Id (UTF8-BASE64-URL-encoded)
          required: true
          style: simple
          explode: true
          schema:
            type: string
            format: byte
      requestBody:
        description: AASX package
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                aasIds:
                  type: array
                  items:
                    type: string
                file:
                  type: string
                  format: binary
                fileName:
                  type: string
            encoding:
              file:
                contentType: application/asset-administration-shell-package
        required: true
      responses:
        '204':
          description: AASX package updated successfully
        '400':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/bad-request'
        '404':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/not-found'
        '500':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/internal-server-error'    
        default:
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/default'
    delete:
      tags:
        - AASX File Server API
      summary: Deletes a specific AASX package from the server
      operationId: DeleteAASXByPackageId
      x-semanticIds:
        - https://admin-shell.io/aas/API/DeleteAASXByPackageId/3/0
      parameters:
        - name: packageId
          in: path
          description: The Package Id (UTF8-BASE64-URL-encoded)
          required: true
          style: simple
          explode: true
          schema:
            type: string
            format: byte
      responses:
        '204':
          description: Deleted successfully
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/schemas/Result'      
        default:
          description: Default error handling for unmentioned status codes
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/schemas/Result'
  /description:
    get:
      tags:
        - Description API
      summary: Returns the self-describing information of a network resource (Description)
      operationId: GetDescription
      x-semanticIds:
        - https://admin-shell.io/aas/API/Descriptor/GetDescription/3/0
      responses:
        '200':
          description: Requested Description
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/schemas/Description'
        '403':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/responses/forbidden'