openapi: 3.0.3
info:
  title: DotAAS Part 2 | HTTP/REST | AASX File Server Service Specification
  description: >-
    The async profile of the File Server Service Specification as part of the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub).

    Publisher: Industrial Digital Twin Association (IDTA) 2026
  contact:
    name: Industrial Digital Twin Association (IDTA)
    email: info@idtwin.org
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  version: V3.2.0_SSP-002
  x-profile-identifier: https://admin-shell.io/aas/API/3/2/AasxFileServerServiceSpecification/SSP-002
  termsOfService: https://github.com/admin-shell-io/aas-specs
servers:
- url: 'https://admin-shell.io/api/v3'
- url: 'https://example.com'
paths:
  /packages-async:
  
    post:
      tags:
        - AASX Async File Server API
      summary: Initiates an asynchronous upload of an AASX package at the server.
      operationId: PostAsyncAASXPackage
      x-semanticIds:
        - https://admin-shell.io/aas/API/PostAsyncAASXPackage/3/2
      requestBody:
        description: AASX package
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                aasIds:
                  type: array
                  items:
                    type: string
                file:
                  type: string
                  format: binary
                fileName:
                  type: string
            encoding:
              file:
                contentType: application/asset-administration-shell-package
        required: true
      responses:
        '202':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/accepted'
        '400':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/bad-request'
        '401':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/unauthorized'
        '403':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/forbidden'
        '409':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/conflict'
        '500':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/internal-server-error'
        default:
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/default'
  
  /packages-async/status/{handleId}:
    parameters:
      - $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/parameters/HandleId'
    get:
      tags:
        - AASX Async File Server Status API
      summary: Returns the status of an asynchronously invoked AASX operation.
      operationId: GetAasxAsyncStatus
      x-semanticIds:
        - https://admin-shell.io/aas/API/GetAasxAsyncStatus/3/2
      responses:
        '200':
          description: Operation result object containing information that the 'executionState' is still 'Running'
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/schemas/BaseOperationResult'
        '302':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/found'
        '400':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/bad-request'
        '401':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/unauthorized'
        '403':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/forbidden'
        '404':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/not-found'
        '500':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/internal-server-error'
        default:
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/default'
  /packages-async/results/{handleId}:
    parameters:
      - $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/parameters/HandleId'
    get:
      tags:
        - AASX Async File Server Result API
      summary: Returns the result of an asynchronously invoked AASX operation.
      operationId: GetAasxAsyncResult
      x-semanticIds:
        - https://admin-shell.io/aas/API/GetAasxAsyncResult/3/2
      responses:
        '200':
          description: Operation result object
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/schemas/BaseOperationResult'
        '400':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/bad-request'
        '401':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/unauthorized'
        '403':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/forbidden'
        '404':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/not-found'
        '500':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/internal-server-error'
        default:
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/default'


  /description:
    get:
      tags:
        - Description API
      summary: Returns the self-describing information of a network resource (ServiceDescription)
      operationId: GetDescription
      x-semanticIds:
        - https://admin-shell.io/aas/API/Descriptor/GetDescription/3/2
      responses:
        '200':
          description: Requested Description
          content:
            application/json:
              example: "https://admin-shell.io/aas/API/3/2/AasxFileServerServiceSpecification/SSP-002"
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/schemas/ServiceDescription'
        '400':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/bad-request'
        '403':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/forbidden'
        '404':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/not-found'
        '500':
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/internal-server-error'
        default:
          $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.2.0#/components/responses/default'